ccflags-y += -Idrivers/gpu/drm/tegra
ccflags-y += -I../t18x/drivers/gpu/drm/tegra

tegra-drm-t186-y = \
	vic_t186.o \
	nvenc_t186.o \
	nvdec_t186.o \
	nvjpg_t186.o \
	tsec_t186.o

obj-$(CONFIG_TEGRA_HOST1X) += tegra-drm-t186.o
