##
# 
##

# MODULE is SERVER_INIT

SERVER_INIT_DIR=$${MODULES_DIR}/server_init
SERVER_INIT_INTERFACE=$(SERVER_INIT_DIR)/interface
SERVER_INIT_SOURCES=$(SERVER_INIT_DIR)/src

SERVER_INIT_FW_FILES  = $(SERVER_INIT_SOURCES)/ia_css_server_init_cell.c
SERVER_INIT_FW_FILES += $(SERVER_INIT_SOURCES)/ia_css_server_offset.c
SERVER_INIT_FW_CPPFLAGS = -I$(SERVER_INIT_INTERFACE)

SERVER_INIT_HOST_FILES  = $(SERVER_INIT_SOURCES)/ia_css_server_init_host.c
SERVER_INIT_HOST_FILES += $(SERVER_INIT_SOURCES)/ia_css_server_offset.c
SERVER_INIT_HOST_CPPFLAGS = -I$(SERVER_INIT_INTERFACE)

