# 
#
ifndef REGMEM_MK
REGMEM_MK=1

# MODULE is REGMEM

REGMEM_DIR=$${MODULES_DIR}/regmem

REGMEM_INTERFACE=$(REGMEM_DIR)/interface
REGMEM_SOURCES=$(REGMEM_DIR)/src

REGMEM_HOST_FILES =
REGMEM_FW_FILES =

REGMEM_CPPFLAGS = -I$(REGMEM_INTERFACE) -I$(REGMEM_SOURCES)
REGMEM_HOST_CPPFLAGS = $(REGMEM_CPPFLAGS)
REGMEM_FW_CPPFLAGS = $(REGMEM_CPPFLAGS)

endif
