# 
#
# MODULE Trace

# Dependencies
IA_CSS_TRACE_SUPPORT = $${MODULES_DIR}/support

# API
IA_CSS_TRACE = $${MODULES_DIR}/trace
IA_CSS_TRACE_INTERFACE = $(IA_CSS_TRACE)/interface

#
# Host
#

# Host CPP Flags
IA_CSS_TRACE_HOST_CPPFLAGS += -I$(IA_CSS_TRACE_SUPPORT)
IA_CSS_TRACE_HOST_CPPFLAGS += -I$(IA_CSS_TRACE_INTERFACE)
IA_CSS_TRACE_HOST_CPPFLAGS += -I$(IA_CSS_TRACE)/trace_modules

#
# Firmware
#

# Firmware CPP Flags
IA_CSS_TRACE_FW_CPPFLAGS += -I$(IA_CSS_TRACE_SUPPORT)
IA_CSS_TRACE_FW_CPPFLAGS += -I$(IA_CSS_TRACE_INTERFACE)
IA_CSS_TRACE_FW_CPPFLAGS += -I$(IA_CSS_TRACE)/trace_modules
