##
# 
##

# MODULE is cpd/cpd_component

CPD_DIR				= $${MODULES_DIR}/cpd
CPD_COMPONENT_DIR		= $${MODULES_DIR}/cpd/cpd_component
CPD_COMPONENT_INTERFACE		= $(CPD_COMPONENT_DIR)/interface
CPD_COMPONENT_SOURCES		= $(CPD_COMPONENT_DIR)/src

CPD_COMPONENT_FILES		= $(CPD_COMPONENT_SOURCES)/ia_css_cpd_component_create.c
CPD_COMPONENT_FILES		+= $(CPD_COMPONENT_SOURCES)/ia_css_cpd_component.c
CPD_COMPONENT_CPPFLAGS		= -I$(CPD_COMPONENT_INTERFACE)
CPD_COMPONENT_CPPFLAGS		+= -I$(CPD_COMPONENT_SOURCES)
CPD_COMPONENT_CPPFLAGS		+= -I$(CPD_DIR)
