# 
#

ifndef _DEVICE_ACCESS_MK_
_DEVICE_ACCESS_MK_ = 1

DEVICE_ACCESS_DIR=$${MODULES_DIR}/device_access
DEVICE_ACCESS_INTERFACE=$(DEVICE_ACCESS_DIR)/interface
DEVICE_ACCESS_SOURCES=$(DEVICE_ACCESS_DIR)/src

DEVICE_ACCESS_HOST_FILES =

DEVICE_ACCESS_FW_FILES =

DEVICE_ACCESS_HOST_CPPFLAGS = \
	-I$(DEVICE_ACCESS_INTERFACE) \
	-I$(DEVICE_ACCESS_SOURCES)

DEVICE_ACCESS_FW_CPPFLAGS = \
	-I$(DEVICE_ACCESS_INTERFACE) \
	-I$(DEVICE_ACCESS_SOURCES)

ifeq "$(IPU_SYSVER)" "cnlA0"
	DEVICE_ACCESS_VERSION=v2
endif
ifeq "$(IPU_SYSVER)" "cnlB0"
	DEVICE_ACCESS_VERSION=v2
endif
ifeq "$(IPU_SYSVER)" "glvA0"
	DEVICE_ACCESS_VERSION=v2
endif
ifeq "$(IPU_SYSVER)" "bxtA0"
	DEVICE_ACCESS_VERSION=v1
endif
ifeq "$(IPU_SYSVER)" "bxtB0"
	DEVICE_ACCESS_VERSION=v2
endif

DEVICE_ACCESS_FW_CPPFLAGS += \
		-I$(DEVICE_ACCESS_SOURCES)/$(DEVICE_ACCESS_VERSION)
endif
