# compat26/Makefile
#
# Copyright 2016 Codethink Ltd

# core consists of the core code written by Codethink
# tegra is code to support tegra specific APIs written by Codethink
# tegra26 is code from the 2.6 tegra kernel (possibly modified)

obj-$(CONFIG_TEGRA_COMPAT_26)	+= core/
obj-$(CONFIG_TEGRA_COMPAT_26)	+= tegra/
obj-$(CONFIG_TEGRA_COMPAT_26)	+= tegra26/

obj-$(CONFIG_TEGRA_PDK_25_023) += pdk25_023/
obj-$(CONFIG_TEGRA_PDK_19_006) += pdk19_006/
