ccflags-y                            += -DNV_DEBUG=0
obj-$(CONFIG_EMBEDDED_TEGRA_PCM)     += tegra_pcm.o
obj-$(CONFIG_EMBEDDED_TEGRA_I2S)     += tegra_i2s.o tegra_soc_i2s.o
obj-$(CONFIG_EMBEDDED_TEGRA_TDM)     += tegra_tdm.o tegra_soc_tdm.o
obj-${CONFIG_TEGRA_DUMMY_CODEC}      += dummy_codec.o
obj-$(CONFIG_EMBEDDED_TEGRA_SPI_I2S) += tegra_card_spi_i2s.o tegra_pcm_spi_i2s.o tegra_codec_spi_i2s.o tegra_dai_spi_i2s.o
obj-$(CONFIG_EMBEDDED_TEGRA_ALSA_SPDIF)   += tegra_spdif.o tegra_soc_spdif.o


