/*
 * Copyright (c) 2014--2015 Intel Corporation.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version
 * 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */

#ifndef INTEL_IPU4_BUTTRESS_REGS_H
#define INTEL_IPU4_BUTTRESS_REGS_H

#define BUTTRESS_REG_IS_FREQ_CTL	0x34
#define BUTTRESS_REG_PS_FREQ_CTL	0x38

#define BUTTRESS_FREQ_CTL_START_SHIFT		31
#define BUTTRESS_FREQ_CTL_RATIO_MASK		0xff
#define BUTTRESS_FREQ_CTL_QOS_FLOOR_SHIFT	8
#define BUTTRESS_FREQ_CTL_QOS_FLOOR_MASK	(0xff << 8)

#define BUTTRESS_REG_PWR_STATE	0x5c

#define BUTTRESS_PWR_STATE_IS_PWR_SHIFT	4
#define BUTTRESS_PWR_STATE_IS_PWR_MASK	(0x7 << 4)

#define BUTTRESS_PWR_STATE_PS_PWR_SHIFT	8
#define BUTTRESS_PWR_STATE_PS_PWR_MASK	(0x7 << 8)

#define BUTTRESS_PWR_STATE_RESET		0x0
#define BUTTRESS_PWR_STATE_PWR_ON_DONE		0x1
#define BUTTRESS_PWR_STATE_PWR_RDY		0x3
#define BUTTRESS_PWR_STATE_PWR_IDLE		0x4

#define BUTTRESS_PWR_STATE_HH_STATUS_SHIFT	12
#define BUTTRESS_PWR_STATE_HH_STATUS_MASK	(0x3 << 12)

enum {
	BUTTRESS_PWR_STATE_HH_STATE_IDLE,
	BUTTRESS_PWR_STATE_HH_STATE_IN_PRGS,
	BUTTRESS_PWR_STATE_HH_STATE_DONE,
	BUTTRESS_PWR_STATE_HH_STATE_ERR,
};

#define BUTTRESS_REG_SECURITY_CTL	0x300

#define BUTTRESS_SECURITY_CTL_FW_SECURE_MODE_SHIFT	16

#define BUTTRESS_REG_SECURE_TOUCH	0x318

#define BUTTRESS_SECURE_TOUCH_SECURE_TOUCH_SHIFT	31

#define BUTTRESS_REG_SENSOR_FREQ_CTL	0x16c

#define BUTTRESS_SENSOR_FREQ_CTL_LJPLL_FB_RATIO_MASK		0xff
#define BUTTRESS_SENSOR_FREQ_CTL_SEL_MIPICLK_A_SHIFT		8
#define BUTTRESS_SENSOR_FREQ_CTL_SEL_MIPICLK_A_MASK		(0x2 << 8)
#define BUTTRESS_SENSOR_FREQ_CTL_SEL_MIPICLK_C_SHIFT		10
#define BUTTRESS_SENSOR_FREQ_CTL_SEL_MIPICLK_C_MASK		(0x2 << 10)
#define BUTTRESS_SENSOR_FREQ_CTL_LJPLL_FORCE_OFF_SHIFT		12
#define BUTTRESS_SENSOR_FREQ_CTL_LJPLL_REF_RATIO_SHIFT		14
#define BUTTRESS_SENSOR_FREQ_CTL_LJPLL_REF_RATIO_MASK		(0x2 << 14)
#define BUTTRESS_SENSOR_FREQ_CTL_LJPLL_PVD_RATIO_SHIFT		16
#define BUTTRESS_SENSOR_FREQ_CTL_LJPLL_PVD_RATIO_MASK		(0x2 << 16)
#define BUTTRESS_SENSOR_FREQ_CTL_LJPLL_OUTPUT_RATIO_SHIFT	18
#define BUTTRESS_SENSOR_FREQ_CTL_LJPLL_OUTPUT_RATIO_MASK	(0x2 << 18)
#define BUTTRESS_SENSOR_FREQ_CTL_START_SHIFT			31

#define BUTTRESS_REG_SENSOR_CLK_CTL	0x170

/* 0 <= i <= 2 */
#define BUTTRESS_SENSOR_CLK_CTL_OSC_CLK_OUT_EN_SHIFT(i)		((i) * 2)
#define BUTTRESS_SENSOR_CLK_CTL_OSC_CLK_OUT_SEL_SHIFT(i)	((1) * 2 + 1)

#define BUTTRESS_REG_FW_SOURCE_BASE_LO	0x78
#define BUTTRESS_REG_FW_SOURCE_BASE_HI	0x7C
#define BUTTRESS_REG_FW_SOURCE_SIZE	0x80

#define BUTTRESS_REG_ISR_STATUS		0x90
#define BUTTRESS_REG_ISR_ENABLED_STATUS	0x94
#define BUTTRESS_REG_ISR_ENABLE		0x98
#define BUTTRESS_REG_ISR_CLEAR		0x9C

#define BUTTRESS_ISR_IS_IRQ			(1 << 0)
#define BUTTRESS_ISR_PS_IRQ			(1 << 1)
#define BUTTRESS_ISR_IPC_EXEC_DONE_BY_CSE	(1 << 2)
#define BUTTRESS_ISR_IPC_EXEC_DONE_BY_ISH	(1 << 3)
#define BUTTRESS_ISR_IPC_FROM_CSE_IS_WAITING	(1 << 4)
#define BUTTRESS_ISR_IPC_FROM_ISH_IS_WAITING	(1 << 5)
#define BUTTRESS_ISR_CSE_CSR_SET		(1 << 6)
#define BUTTRESS_ISR_ISH_CSR_SET		(1 << 7)
#define BUTTRESS_ISR_SPURIOUS_CMP		(1 << 8)
#define BUTTRESS_ISR_WATCHDOG_EXPIRED		(1 << 9)
#define BUTTRESS_ISR_PUNIT_2_IUNIT_IRQ		(1 << 10)
#define BUTTRESS_ISR_SAI_VIOLATION		(1 << 11)

#define BUTTRESS_REG_IU2CSEDB0	0x100

#define BUTTRESS_IU2CSEDB0_BUSY_SHIFT		31
#define BUTTRESS_IU2CSEDB0_SHORT_FORMAT_SHIFT	27
#define BUTTRESS_IU2CSEDB0_CLIENT_ID_SHIFT	10
#define BUTTRESS_IU2CSEDB0_IPC_CLIENT_ID_VAL	2

#define BUTTRESS_REG_IU2CSEDATA0	0x104

#define BUTTRESS_IU2CSEDATA0_IPC_BOOT_LOAD		1
#define BUTTRESS_IU2CSEDATA0_IPC_AUTHENTICATE_RUN	2
#define BUTTRESS_IU2CSEDATA0_IPC_AUTHENTICATE_REPLACE	3
#define BUTTRESS_IU2CSEDATA0_IPC_UPDATE_SECURE_TOUCH	16

#define BUTTRESS_REG_IU2CSECSR		0x108

#define BUTTRESS_IU2CSECSR_IPC_PEER_COMP_ACTIONS_RST_PHASE1		(1 << 0)
#define BUTTRESS_IU2CSECSR_IPC_PEER_COMP_ACTIONS_RST_PHASE2		(1 << 1)
#define BUTTRESS_IU2CSECSR_IPC_PEER_QUERIED_IP_COMP_ACTIONS_RST_PHASE	(1 << 2)
#define BUTTRESS_IU2CSECSR_IPC_PEER_ASSERTED_REG_VALID_REQ		(1 << 3)
#define BUTTRESS_IU2CSECSR_IPC_PEER_ACKED_REG_VALID			(1 << 4)
#define BUTTRESS_IU2CSECSR_IPC_PEER_DEASSERTED_REG_VALID_RE		(1 << 5)

#define BUTTRESS_REG_CSE2IUDB0		0x304
#define BUTTRESS_REG_CSE2IUCSR		0x30C
#define BUTTRESS_REG_CSE2IUDATA0	0x308

#define BUTTRESS_REG_ISH2IUCSR		0x50
#define BUTTRESS_REG_ISH2IUDB0		0x54
#define BUTTRESS_REG_ISH2IUDATA0	0x58

#define BUTTRESS_REG_IU2ISHDB0		0x10C
#define BUTTRESS_REG_IU2ISHDATA0	0x110
#define BUTTRESS_REG_IU2ISHDATA1	0x114
#define BUTTRESS_REG_IU2ISHCSR		0x118

#define BUTTRESS_REG_ISH_START_DETECT		0x198
#define BUTTRESS_REG_ISH_START_DETECT_MASK	0x19C

#define BUTTRESS_REG_CSE_ACTION	0x310

#define BUTTRESS_CSE_ACTION_MASK	0x7f

#define BUTTRESS_CSE_ACTION_SETUP_STARTED    1
#define BUTTRESS_CSE_ACTION_SETUP_DONE       2
#define BUTTRESS_CSE_ACTION_BASE_AUTH_DONE   4
#define BUTTRESS_CSE_ACTION_BASE_AUTH_FAILED 8
#define BUTTRESS_CSE_ACTION_NEW_AUTH_STARTED 64
#define BUTTRESS_CSE_ACTION_NEW_AUTH_DONE    16
#define BUTTRESS_CSE_ACTION_NEW_AUTH_FAILED  32

#define BUTTRESS_REG_FABRIC_CMD	0x88

#define BUTTRESS_FABRIC_CMD_START_TSC_SYNC	(1 << 0)
#define BUTTRESS_FABRIC_CMD_IS_DRAIN		(1 << 4)

#define BUTTRESS_REG_TSW_CTL		0x120
#define BUTTRESS_TSW_CTL_SOFT_RESET	(1 << 8)

#define BUTTRESS_REG_TSC_LO	0x164
#define BUTTRESS_REG_TSC_HI	0x168

#define BUTTRESS_REG_CSI2_PORT_CONFIG_AB		0x200
#define BUTTRESS_CSI2_PORT_CONFIG_AB_MUX_MASK		0x1f
#define BUTTRESS_CSI2_PORT_CONFIG_AB_COMBO_SHIFT_A0	8
#define BUTTRESS_CSI2_PORT_CONFIG_AB_COMBO_SHIFT_B0	16

#endif /* INTEL_IPU4_BUTTRESS_REGS_H */
