/*
 * Copyright (c) 2016 Intel Corporation.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version
 * 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */

#ifndef INTEL_IPU5_ISYS_CSI2_REG_H
#define INTEL_IPU5_ISYS_CSI2_REG_H

#define INTEL_IPU5_CSI2_REG_CSI_RX_ENABLE				0x00
#define INTEL_IPU5_CSI2_CSI_RX_ENABLE_ENABLE			0x01
/* Enabled lanes - 1 */
#define INTEL_IPU5_CSI2_REG_CSI_RX_NOF_ENABLED_LANES		0x04
#define INTEL_IPU5_CSI2_REG_CSI_RX_CONFIG				0x08
#define INTEL_IPU5_CSI2_CSI_RX_CONFIG_RELEASE_LP11			0x1
#define INTEL_IPU5_CSI2_CSI_RX_CONFIG_DISABLE_BYTE_CLK_GATING	0x2
#define INTEL_IPU5_CSI2_REG_CSI_RX_HBP_TESTMODE_ENABLE		0x0c
#define INTEL_IPU5_CSI2_REG_CSI_RX_ENABLE_SECURE_TOUCH		0x10
#define INTEL_IPU5_CSI2_REG_CSI_RX_ERROR_HANDLING			0x14
#define INTEL_IPU5_CSI2_REG_CSI_RX_SP_IF_CONFIG			0x18
#define INTEL_IPU5_CSI2_REG_CSI_RX_LP_IF_CONFIG			0x1C
#define INTEL_IPU5_CSI2_REG_CSI_RX_STATUS				0x20
#define INTEL_IPU5_CSI2_CSI_RX_STATUS_BUSY				0x01
#define INTEL_IPU5_CSI2_REG_CSI_RX_STATUS_DLANE_HS			0x24
#define INTEL_IPU5_CSI2_REG_CSI_RX_STATUS_DLANE_LP			0x28
#define INTEL_IPU5_CSI2_REG_CSI_RX_DLY_CNT_TERMEN_CLANE		0x2c
#define INTEL_IPU5_CSI2_REG_CSI_RX_DLY_CNT_SETTLE_CLANE		0x30
/* 0..3 */
#define INTEL_IPU5_CSI2_REG_CSI_RX_DLY_CNT_TERMEN_DLANE(n)		\
			(0x34 + (n) * 8)
#define INTEL_IPU5_CSI2_REG_CSI_RX_DLY_CNT_SETTLE_DLANE(n)		\
			(0x38 + (n) * 8)

#define INTEL_IPU5_CSI2_CSI_RX_DLY_CNT_TERMEN_CLANE_A		0
#define INTEL_IPU5_CSI2_CSI_RX_DLY_CNT_TERMEN_CLANE_B		0
#define INTEL_IPU5_CSI2_CSI_RX_DLY_CNT_SETTLE_CLANE_A		95
#define INTEL_IPU5_CSI2_CSI_RX_DLY_CNT_SETTLE_CLANE_B		-8

#define INTEL_IPU5_CSI2_CSI_RX_DLY_CNT_TERMEN_DLANE_A		0
#define INTEL_IPU5_CSI2_CSI_RX_DLY_CNT_TERMEN_DLANE_B		0
#define INTEL_IPU5_CSI2_CSI_RX_DLY_CNT_SETTLE_DLANE_A		85
#define INTEL_IPU5_CSI2_CSI_RX_DLY_CNT_SETTLE_DLANE_B		-2

/* IRQ-related registers specific to each of the four CSI receivers */
#define INTEL_IPU5_CSI2_REG_CSI2PART_IRQ_EDGE			0x400
#define INTEL_IPU5_CSI2_REG_CSI2PART_IRQ_MASK			0x404
#define INTEL_IPU5_CSI2_REG_CSI2PART_IRQ_STATUS			0x408
#define INTEL_IPU5_CSI2_REG_CSI2PART_IRQ_CLEAR			0x40c
#define INTEL_IPU5_CSI2_REG_CSI2PART_IRQ_ENABLE			0x410
#define INTEL_IPU5_CSI2_REG_CSI2PART_IRQ_LEVEL_NOT_PULSE		0x414
#define INTEL_IPU5_CSI2_CSI2PART_IRQ_CSIRX_B0			0x10000
#define INTEL_IPU5_CSI2_CSI2PART_IRQ_CSI2S2M_B0			0x20000

#define INTEL_IPU5_CSI2_REG_CSIRX_IRQ_EDGE				0x500
#define INTEL_IPU5_CSI2_REG_CSIRX_IRQ_MASK				0x504
#define INTEL_IPU5_CSI2_REG_CSIRX_IRQ_STATUS			0x508
#define INTEL_IPU5_CSI2_REG_CSIRX_IRQ_CLEAR			0x50c
#define INTEL_IPU5_CSI2_REG_CSIRX_IRQ_ENABLE			0x510
#define INTEL_IPU5_CSI2_REG_CSIRX_IRQ_LEVEL_NOT_PULSE		0x514
#define INTEL_IPU5_CSI2_CSIRX_HEADER_SINGLE_ERROR_CORRECTED	BIT(0)
#define INTEL_IPU5_CSI2_CSIRX_HEADER_MULTIPLE_ERRORS_CORRECTED	BIT(1)
#define INTEL_IPU5_CSI2_CSIRX_PAYLOAD_CRC_ERROR			BIT(2)
#define INTEL_IPU5_CSI2_CSIRX_FIFO_OVERFLOW			BIT(3)
#define INTEL_IPU5_CSI2_CSIRX_RESERVED_SHORT_PACKET_DATA_TYPE	BIT(4)
#define INTEL_IPU5_CSI2_CSIRX_RESERVED_LONG_PACKET_DATA_TYPE	BIT(5)
#define INTEL_IPU5_CSI2_CSIRX_INCOMPLETE_LONG_PACKET		BIT(6)
#define INTEL_IPU5_CSI2_CSIRX_FRAME_SYNC_ERROR			BIT(7)
#define INTEL_IPU5_CSI2_CSIRX_LINE_SYNC_ERROR			BIT(8)
#define INTEL_IPU5_CSI2_CSIRX_DPHY_RECOVERABLE_SYNC_ERROR		BIT(9)
#define INTEL_IPU5_CSI2_CSIRX_DPHY_NONRECOVERABLE_SYNC_ERROR	BIT(10)
#define INTEL_IPU5_CSI2_CSIRX_ESCAPE_MODE_ERROR			BIT(11)
#define INTEL_IPU5_CSI2_CSIRX_ESCAPE_MODE_TRIGGER_EVENT		BIT(12)
#define INTEL_IPU5_CSI2_CSIRX_ESCAPE_MODE_ULTRALOW_POWER_DATA	BIT(13)
#define INTEL_IPU5_CSI2_CSIRX_ESCAPE_MODE_ULTRALOW_POWER_EXIT_CLK	BIT(14)
#define INTEL_IPU5_CSI2_CSIRX_INTER_FRAME_SHORT_PACKET_DISCARDED	BIT(15)
#define INTEL_IPU5_CSI2_CSIRX_INTER_FRAME_LONG_PACKET_DISCARDED	BIT(16)
#define INTEL_IPU5_CSI2_CSIRX_NUM_ERRORS				17

#define INTEL_IPU5_CSI2_REG_CSI2S2M_IRQ_EDGE			0x600
#define INTEL_IPU5_CSI2_REG_CSI2S2M_IRQ_MASK			0x604
#define INTEL_IPU5_CSI2_REG_CSI2S2M_IRQ_STATUS			0x608
#define INTEL_IPU5_CSI2_REG_CSI2S2M_IRQ_CLEAR			0x60c
#define INTEL_IPU5_CSI2_REG_CSI2S2M_IRQ_ENABLE			0x610
#define INTEL_IPU5_CSI2_REG_CSI2S2M_IRQ_LEVEL_NOT_PULSE		0x614
#define INTEL_IPU5_CSI2_IRQ_FS_VC(chn)		(1 << ((chn) * 4))
#define INTEL_IPU5_CSI2_IRQ_FE_VC(chn)		(2 << ((chn) * 4))
#define INTEL_IPU5_CSI2_IRQ_LS_VC(chn)		(4 << ((chn) * 4))
#define INTEL_IPU5_CSI2_IRQ_LE_VC(chn)		(8 << ((chn) * 4))

/*General purposer registers, offset to gpreg base*/
#define INTEL_IPU5_CSI2_REG_CSI_GPREG_SOFT_RESET			0
#define INTEL_IPU5_CSI2_REG_CSI_GPREG_SOFT_RESET_SLV		0x4
#define INTEL_IPU5_CSI2_REG_CSI_GPREG_HPLL_FREQ			0x8
#define INTEL_IPU5_CSI2_REG_CSI_GPREG_ISCLK_RATIO			0xc
#define INTEL_IPU5_CSI2_REG_CSI_GPREG_HPLL_FREQ_ISCLK_RATIO_OVERRIDE 0x10
#define INTEL_IPU5_CSI2_REG_CSI_GPREG_CR_PORT_CONFIG		0x14
#define INTEL_IPU5_CSI2_REG_CSI_GPREG_RCOMP_TIMER_DISABLE		0x18
#define INTEL_IPU5_CSI2_REG_CSI_GPREG_RCOMP_TIMER_VALUE		0x1c


#endif /* INTEL_IPU5_ISYS_CSI2_REG_H */
