# 
#
# MODULE is PORT

PORT_DIR=$${MODULES_DIR}/port

PORT_INTERFACE=$(PORT_DIR)/interface
PORT_SOURCES1=$(PORT_DIR)/src

PORT_HOST_FILES += $(PORT_SOURCES1)/send_port.c
PORT_HOST_FILES += $(PORT_SOURCES1)/recv_port.c
PORT_HOST_FILES += $(PORT_SOURCES1)/queue.c

PORT_HOST_CPPFLAGS += -I$(PORT_INTERFACE)

PORT_FW_FILES += $(PORT_SOURCES1)/send_port.c
PORT_FW_FILES += $(PORT_SOURCES1)/recv_port.c

ifndef BXT_INTERFACES_ENABLED
	PORT_FW_CPPFLAGS += -I$(PORT_INTERFACE)
endif
