# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_TESLA_AMD_HSTI) += hsti/
obj-$(CONFIG_TESLA_AMD_HSTI1) += hsti1/
obj-$(CONFIG_TESLA_AMD_OEM) += oem/
obj-$(CONFIG_TESLA_AMD_PSB) += psb/
obj-$(CONFIG_TESLA_PANIC_BIOSRAM) += panic-biosram/
