#
# drivers/misc/eqos_ape/Makefile
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# Copyright (c) 2015-2016, NVIDIA CORPORATION.  All rights reserved.
#

obj-$(CONFIG_EQOS_APE_HWDEP) := eqos_ape.o

eqos_ape-objs := \
	eqos_ape_amisc.o \
	eqos_ape_ioctl.o
