obj-$(CONFIG_SYNOPSYS_DWC_QOS_4_21) += snps-dwc-qos.o
snps-dwc-qos-objs := dwc_eth_qos_dev.o dwc_eth_qos_drv.o dwc_eth_qos_desc.o \
                dwc_eth_qos_ethtool.o dwc_eth_qos.o dwc_eth_qos_mdio.o

snps-dwc-qos-$(CONFIG_DWC_QOS_DEBUGFS) += dwc_eth_qos_debug_operation.o
snps-dwc-qos-$(CONFIG_DWC_QOS_PTPSUPPORT) += dwc_eth_qos_ptp.o
