#ifndef _TRIP_REG_H_
#define _TRIP_REG_H_

/* Engine version */
#define TRIP_R_VERSION		0x0

#define TRIP_R_VERSION_ENGINE_NO_MASK	0xffff0000
#define TRIP_R_VERSION_ENGINE_NO_SHIFT	16
#define TRIP_R_VERSION_FAMILY_ID_MASK	0x00000f00
#define TRIP_R_VERSION_FAMILY_ID_SHIFT	8
#define TRIP_R_VERSION_MAJOR_MASK	0x000000f0
#define TRIP_R_VERSION_MAJOR_SHIFT	4
#define TRIP_R_VERSION_MINOR_MASK	0x0000000f
#define TRIP_R_VERSION_MINOR_SHIFT	0

#define TRIP_R_VERSION_MASK		0x0000ffff
#define TRIP_R_VERSION_SHIFT		0
#define TRIP_R_VERSION_A0		0x110

/* AXI slave configuration */
#define TRIP_R_AXI_CFG		0x20

#define TRIP_R_AXI_CFG_CROSSING_DIS_BIT	(1 << 17)
#define TRIP_R_AXI_CFG_SMALL_WR_DIS_BIT (1 << 16)
#define TRIP_R_AXI_CFG_PROTO_CHK_EN_BIT	(1 << 15)
#define TRIP_R_AXI_CFG_AR_Q_SZ_MASK	0x00007c00
#define TRIP_R_AXI_CFG_AR_Q_SZ_SHIFT	10
#define TRIP_R_AXI_CFG_W_Q_SZ_MASK	0x000003e0
#define TRIP_R_AXI_CFG_W_Q_SZ_SHIFT	5
#define TRIP_R_AXI_CFG_AW_Q_SZ_MASK	0x0000001f
#define TRIP_R_AXI_CFG_AW_Q_SZ_SHIFT	0

/* ACE master configuration */
#define TRIP_R_ACE_CFG		0x40

#define TRIP_R_ACE_CFG_STRIPE_ID_BIT		(1 << 29)
#define TRIP_R_ACE_CFG_WRITE_SNOOP0_BIT		(1 << 28)

#define TRIP_R_ACE_CFG_WRITE_TXBURST_MASK	0x0c000000
#define TRIP_R_ACE_CFG_WRITE_TXBURST_SHIFT	26
#define TRIP_R_ACE_CFG_WRITE_TXBURST_NONE	0x00000000
#define TRIP_R_ACE_CFG_WRITE_TXBURST_2		0x04000000
#define TRIP_R_ACE_CFG_WRITE_TXBURST_4		0x08000000

#define TRIP_R_ACE_CFG_READ_TXBURST_MASK	0x03000000
#define TRIP_R_ACE_CFG_READ_TXBURST_SHIFT	24
#define TRIP_R_ACE_CFG_READ_TXBURST_NONE	0x00000000
#define TRIP_R_ACE_CFG_READ_TXBURST_2		0x01000000
#define TRIP_R_ACE_CFG_READ_TXBURST_4		0x02000000

#define TRIP_R_ACE_CFG_WRITE_TXLIMIT_MASK	0x00c00000
#define TRIP_R_ACE_CFG_WRITE_TXLIMIT_SHIFT	22
#define TRIP_R_ACE_CFG_WRITE_TXLIMIT_32		0x00000000
#define TRIP_R_ACE_CFG_WRITE_TXLIMIT_24		0x00400000
#define TRIP_R_ACE_CFG_WRITE_TXLIMIT_16		0x00800000

#define TRIP_R_ACE_CFG_READ_TXLIMIT_MASK	0x00300000
#define TRIP_R_ACE_CFG_READ_TXLIMIT_SHIFT	20
#define TRIP_R_ACE_CFG_READ_TXLIMIT_96		0x00000000
#define TRIP_R_ACE_CFG_READ_TXLIMIT_64		0x00100000
#define TRIP_R_ACE_CFG_READ_TXLIMIT_32		0x00200000

#define TRIP_R_ACE_CFG_DATA_ARDOMAIN_MASK	0x000c0000
#define TRIP_R_ACE_CFG_DATA_ARDOMAIN_SHIFT	18

#define TRIP_R_ACE_CFG_WEIGHT_ARDOMAIN_MASK	0x00030000
#define TRIP_R_ACE_CFG_WEIGHT_ARDOMAIN_SHIFT	16

#define TRIP_R_ACE_CFG_DATA_ARCACHE_MASK	0x0000f000
#define TRIP_R_ACE_CFG_DATA_ARCACHE_SHIFT	12

#define TRIP_R_ACE_CFG_WEIGHT_ARCACHE_MASK	0x00000f00
#define TRIP_R_ACE_CFG_WEIGHT_ARCACHE_SHIFT	8

#define TRIP_R_ACE_CFG_AWCACHE_MASK		0x000000f0
#define TRIP_R_ACE_CFG_AWCACHE_SHIFT		4

#define TRIP_R_ACE_CFG_AWDOMAIN_MASK		0x0000000c
#define TRIP_R_ACE_CFG_AWDOMAIN_SHIFT		2

#define TRIP_R_ACE_CFG_STRIPE_GRANULE_BIT	(1 << 1)
#define TRIP_R_ACE_CFG_STRIPE_GRANULE_1K	(0 << 1)
#define TRIP_R_ACE_CFG_STRIPE_GRANULE_2K	(1 << 1)

#define TRIP_R_ACE_CFG_STRIPE_WEIGHTS_BIT	(1 << 0)

/* SRAM bank configuration */
#define TRIP_R_SRAM_CFG		0x80

#define TRIP_R_SRAM_CFG_FILL_STALL_THRESH_MASK	0x003f0000
#define TRIP_R_SRAM_CFG_FILL_STALL_THRESH_SHIFT	16

#define TRIP_R_SRAM_CFG_WCB_STALL_THRESH_MASK	0x0000ff00
#define TRIP_R_SRAM_CFG_WCB_STALL_THRESH_SHIFT	8

/*
 * Per-network registers where each network's instance is separated by an
 * offset of TRIP_R_NET_OFFSET.  Number of instances is TRIP_NET_MAX.
 *
 * 0x200-0x3e0: network control registers
 * 0x400-0x5e0: newwork input data base registers
 * 0x600-0x7e0: network input weight base registers
 * 0x800-0x9e0: network output data base registers
 * 0xa00-0xbe0: network status registers
 */
#define TRIP_R_NET_OFFSET	0x20
#define TRIP_NET_MAX		16

/* Engine network control */
#define TRIP_R_NW_CONTROL		0x200

#define TRIP_R_NW_CONTROL_INT_EN_BIT		(1 << 31)
#define TRIP_R_NW_CONTROL_CODE_ADDR_MASK	0x01ffffe0
#define TRIP_R_NW_CONTROL_CODE_ADDR_SHIFT	0

/* Netwwork base registers */
#define TRIP_R_INPUT_DATA_BASE		0x400
#define TRIP_R_INPUT_WEIGHT_BASE	0x600
#define TRIP_R_OUTPUT_BASE		0x800

#define TRIP_BASE_ADDR_MASK			0x3fffffff
#define TRIP_BASE_ADDR(addr)			\
			(((addr) >> 6) & TRIP_BASE_ADDR_MASK)

/* Engine network status */
#define TRIP_R_NW_STATUS		0xa00

#define TRIP_R_NW_STATUS_INT_EN_BIT		(1 << 30)

#define TRIP_R_NW_STATUS_CODE_ADDR_MASK		0x3ffffc00
#define TRIP_R_NW_STATUS_CODE_ADDR_SHIFT	10

#define TRIP_R_NW_STATUS_ERROR_TYPE_MASK	0x000003f0
#define TRIP_R_NW_STATUS_ERROR_TYPE_SHIFT	4

#define TRIP_R_NW_STATUS_ERROR_NONE		0x0
#define TRIP_R_NW_STATUS_ERROR_BADCMD		0x1
#define TRIP_R_NW_STATUS_ERROR_SRAM		0x2
#define TRIP_R_NW_STATUS_ERROR_CRCDMA		0x3
#define TRIP_R_NW_STATUS_ERROR_ACEDMA		0x4
#define TRIP_R_NW_STATUS_ERROR_AXISLV		0x5
#define TRIP_R_NW_STATUS_ERROR_FPINVL		0x6
#define TRIP_R_NW_STATUS_ERROR_FPDENORM		0x7
#define TRIP_R_NW_STATUS_ERROR_FPOVFL		0x8
#define TRIP_R_NW_STATUS_ERROR_FPUNFL		0x9
#define TRIP_R_NW_STATUS_ERROR_HWA		0xa
#define TRIP_R_NW_STATUS_ERROR_WDT		0xb

#define TRIP_R_NW_STATUS_ERROR_BIT		(1 << 3)
#define TRIP_R_NW_STATUS_COMPLETE_BIT		(1 << 2)
#define TRIP_R_NW_STATUS_RUNNING_BIT		(1 << 1)
#define TRIP_R_NW_STATUS_PENDING_BIT		(1 << 0)

#define TRIP_R_NW_STATUS_OUT			\
	(TRIP_R_NW_STATUS_ERROR_TYPE_MASK |	\
	 TRIP_R_NW_STATUS_ERROR_BIT |		\
	 TRIP_R_NW_STATUS_COMPLETE_BIT |	\
	 TRIP_R_NW_STATUS_RUNNING_BIT |		\
	 TRIP_R_NW_STATUS_PENDING_BIT)

/* Interrupt pending status */
#define TRIP_R_INTERRUPT_PENDING	0xe00

#define TRIP_R_INTERRUPT_PENDING_ERROR_MASK		0xffff0000
#define TRIP_R_INTERRUPT_PENDING_ERROR_SHIFT		16
#define TRIP_R_INTERRUPT_PENDING_COMPLETION_MASK	0x0000ffff
#define TRIP_R_INTERRUPT_PENDING_COMPLETION_SHIFT	0
#define TRIP_R_INTERRUPT_PENDING_ERROR(n)		\
		(1 << ((n) + TRIP_R_INTERRUPT_PENDING_ERROR_SHIFT))
#define TRIP_R_INTERRUPT_PENDING_COMPLETION(n)		\
		(1 << ((n) + TRIP_R_INTERRUPT_PENDING_COMPLETION_SHIFT))

/* Error interrupt enable */
#define TRIP_R_ERROR_INTERRUPT_ENABLE	0xe20

#define TRIP_R_ERROR_INTERRUPT_ENABLE_PARITY_ERR	(1 << 1)

/* Watchdog progress control register */
#define TRIP_R_WDT_PROGRESS_CTL		0x1600

#define TRIP_R_WDT_PROGRESS_CTL_MAX_DELAY_MASK		0x1fffffff
#define TRIP_R_WDT_PROGRESS_CTL_MAX_DELAY_SHIFT		0
#define TRIP_R_WDT_PROGRESS_CTL_COMP_EN_BIT		(1 << 29)
#define TRIP_R_WDT_PROGRESS_CTL_DMA_OUT_EN_BIT		(1 << 30)
#define TRIP_R_WDT_PROGRESS_CTL_DMA_IN_EN_BIT		(1 << 31)

/* default to reset values */
#define TRIP_WDT_PROGRESS_MIN				0x80

/* Watchdog layer control register */
#define TRIP_R_WDT_LAYER_CTL		0x1620

#define TRIP_R_WDT_LAYER_CTL_MAX_DELAY_MASK		0x7fffffff
#define TRIP_R_WDT_LAYER_CTL_MAX_DELAY_SHIFT		0
#define TRIP_R_WDT_LAYER_CTL_EN_BIT			(1 << 31)

/* default to reset values */
#define TRIP_WDT_LAYER_MIN				0x1000

/* Watchdog network control register */
#define TRIP_R_WDT_NETWORK_CTL		0x1640

#define	TRIP_R_WDT_NETWORK_CTL_MAX_DELAY_MASK		0x7fffffff
#define	TRIP_R_WDT_NETWORK_CTL_MAX_DELAY_SHIFT		0
#define TRIP_R_WDT_NETWORK_CTL_EN_BIT			(1 << 31)

/* default to reset values */
#define TRIP_WDT_NETWORK_MIN				0x400000

/* Interrupt numbers */
#define TRIP_IRQ_ENG_COMP_START	0	/* 0-15 are per-network irqs */
#define TRIP_IRQ_ENG_GENERIC	16
#define TRIP_IRQ_ENG_ERROR	17

/* DMA descriptor */

/* First 64-bit word */
#define TRIP_DMA_DESC_CMD_MASK		0x00000000000000ffUL
#define TRIP_DMA_DESC_CMD_SHIFT		0
#define TRIP_DMA_DESC_DECOMP_BIT	(1UL << 8)
#define TRIP_DMA_DESC_CRC_CHECK_BIT	(1UL << 9)
#define TRIP_DMA_DESC_INPUT_DEP_MASK	0x0000000000078000UL
#define TRIP_DMA_DESC_INPUT_DEP_SHIFT	15
#define TRIP_DMA_DESC_INPUT_DEP_NONE	TRIP_DMA_DESC_INPUT_DEP_MASK
#define TRIP_DMA_DESC_CLEAR_DEP_BIT	(1UL << 19)
#define TRIP_DMA_DESC_DEP_RELEASE_MASK	0x0000000000f00000UL
#define TRIP_DMA_DESC_DEP_RELEASE_SHIFT	20
#define TRIP_DMA_DESC_SRAM_ADDR_MASK	0x00000fffff000000UL
#define TRIP_DMA_DESC_SRAM_ADDR_SHIFT	24
#define TRIP_DMA_DESC_DRAM_ADDR_MASK	0xfffff00000000000UL
#define TRIP_DMA_DESC_DRAM_ADDR_SHIFT	44

/* Second 64-bit word */
#define TRIP_DMA_DESC_BLOCK_LEN_MASK	0x000000000003ffffUL
#define TRIP_DMA_DESC_BLOCK_LEN_SHIFT	0
#define TRIP_DMA_DESC_BUF_SZ_MASK	0x0000000ffffc0000UL
#define TRIP_DMA_DESC_BUF_SZ_SHIFT	18

#define TRIP_DMA_ALIGNMENT_SHIFT	6	/* 64 byte aligned */
#define TRIP_DMA_ALIGNMENT_MASK		\
		(~((1 << TRIP_DMA_ALIGNMENT_SHIFT) - 1))
#define TRIP_DMA_MAX_SIZE		\
		(TRIP_DMA_DESC_BLOCK_LEN_MASK << TRIP_DMA_ALIGNMENT_SHIFT)

enum {
	TRIP_ENG_CMD_DMA_READ_INPUT = 0x42,
	TRIP_ENG_CMD_DMA_WRITE_OUTPUT = 0x45,
	TRIP_ENG_CMD_STOP = 0x9f,
};

#endif /* _TRIP_REG_H_ */

