GCOV_PROFILE := y
ccflags-y := -Werror
ccflags-y += -Idrivers/platform/tegra/nvadsp -I$(srctree)/drivers/platform/tegra/nvadsp -I$(srctree)/include
obj-y += os-t18x.o
obj-y += dev-t18x.o
obj-y += acast.o
