ifndef IPU_STEP
  $(error No IPU_STEP was defined. Stopping.)
endif

TARGET_MODULE:=intel-ipu-virt-$(IPU_STEP)

$(TARGET_MODULE)-objs += ../virtio/intel-ipu4-virtio-common.o


ifdef CONFIG_VIDEO_INTEL_IPU_VIRTIO_BE
	$(TARGET_MODULE)-objs += ../virtio/intel-ipu4-virtio-be-pipeline.o
	$(TARGET_MODULE)-objs += ../virtio/intel-ipu4-virtio-be-bridge.o
	$(TARGET_MODULE)-objs += ../virtio/intel-ipu4-virtio-be.o
	$(TARGET_MODULE)-objs += ../virtio/intel-ipu4-virtio-be-stream.o
else
	$(TARGET_MODULE)-objs += ../virtio/intel-ipu4-virtio-fe-pipeline.o
	$(TARGET_MODULE)-objs += ../virtio/intel-ipu4-virtio-fe-payload.o
	$(TARGET_MODULE)-objs += ../virtio/intel-ipu4-virtio-fe.o
	$(TARGET_MODULE)-objs += ../virtio/intel-ipu4-para-virt-drv.o
endif

obj-$(CONFIG_VIDEO_INTEL_IPU_ACRN) := $(TARGET_MODULE).o
