obj-$(CONFIG_INTEL_IPU4_BXT_RVP_PDATA)	+= intel-ipu4-bxt-rvp-pdata.o
obj-$(CONFIG_INTEL_IPU4_BXT_RVP_PDATA)	+= intel-ipu4-bxt-p-apl-pdata.o
obj-$(CONFIG_INTEL_IPU4_BXT_P_PDATA)   += intel-ipu4-bxt-p-pdata.o
