# 
#
ifndef _CELL_MK_
_CELL_MK_ = 1


CELL_DIR=$${MODULES_DIR}/cell
CELL_INTERFACE=$(CELL_DIR)/interface
CELL_SOURCES=$(CELL_DIR)/src

CELL_HOST_FILES =
CELL_FW_FILES =

CELL_HOST_CPPFLAGS = \
	-I$(CELL_INTERFACE) \
	-I$(CELL_SOURCES)

CELL_FW_CPPFLAGS = \
	-I$(CELL_INTERFACE) \
	-I$(CELL_SOURCES)

ifdef 0
# Disabled until it is decided to go this way or not
include $(MODULES_DIR)/device_access/device_access.mk
CELL_HOST_FILES += $(DEVICE_ACCESS_HOST_FILES)
CELL_FW_FILES += $(DEVICE_ACCESS_FW_FILES)
CELL_HOST_CPPFLAGS += $(DEVICE_ACCESS_HOST_CPPFLAGS)
CELL_FW_CPPFLAGS += $(DEVICE_ACCESS_FW_CPPFLAGS)
endif

endif
