#
# Makefile - Intel ISH client driver
# Copyright (c) 2014-2016, Intel Corporation.
#
#
obj-$(CONFIG_INTEL_ISH_CLIENT) += intel-ishtp-clients.o

ccflags-y += -I$(srctree)/drivers/hid/intel-ish-hid/ishtp
