/*
 * Copyright (c) 2015-2016, NVIDIA CORPORATION.  All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 */

#ifndef _DT_BINDINGS_PADCTRL_TEGRA186_PADS_H
#define _DT_BINDINGS_PADCTRL_TEGRA186_PADS_H

/* IO PAD group */
#define TEGRA_IO_PAD_GROUP_AUDIO	0
#define TEGRA_IO_PAD_GROUP_AUDIO_HV	1
#define TEGRA_IO_PAD_GROUP_CAM		2
#define TEGRA_IO_PAD_GROUP_CONN		3
#define TEGRA_IO_PAD_GROUP_CSIA		4
#define TEGRA_IO_PAD_GROUP_CSIB		5
#define TEGRA_IO_PAD_GROUP_CSIC		6
#define TEGRA_IO_PAD_GROUP_CSID		7
#define TEGRA_IO_PAD_GROUP_CSIE		8
#define TEGRA_IO_PAD_GROUP_CSIF		9
#define TEGRA_IO_PAD_GROUP_DBG		10
#define TEGRA_IO_PAD_GROUP_DMIC_HV	11
#define TEGRA_IO_PAD_GROUP_DSI		12
#define TEGRA_IO_PAD_GROUP_DSIB		13
#define TEGRA_IO_PAD_GROUP_DSIC		14
#define TEGRA_IO_PAD_GROUP_DSID		15
#define TEGRA_IO_PAD_GROUP_EDP		16
#define TEGRA_IO_PAD_GROUP_HDMI_DP0	17
#define TEGRA_IO_PAD_GROUP_HDMI_DP1	18
#define TEGRA_IO_PAD_GROUP_HSIC		19
#define TEGRA_IO_PAD_GROUP_MIPI_BIAS	20
#define TEGRA_IO_PAD_GROUP_PEX_CLK_BIAS	21
#define TEGRA_IO_PAD_GROUP_PEX_CLK1	22
#define TEGRA_IO_PAD_GROUP_PEX_CLK2	23
#define TEGRA_IO_PAD_GROUP_PEX_CLK3	24
#define TEGRA_IO_PAD_GROUP_PEX_CTRL	25
#define TEGRA_IO_PAD_GROUP_SDMMC1_HV	26
#define TEGRA_IO_PAD_GROUP_SDMMC2_HV	27
#define TEGRA_IO_PAD_GROUP_SDMMC3_HV	28
#define TEGRA_IO_PAD_GROUP_SDMMC4	29
#define TEGRA_IO_PAD_GROUP_SPI		30
#define TEGRA_IO_PAD_GROUP_UART		31
#define TEGRA_IO_PAD_GROUP_USB_BIAS	32
#define TEGRA_IO_PAD_GROUP_USB0		33
#define TEGRA_IO_PAD_GROUP_USB1		34
#define TEGRA_IO_PAD_GROUP_USB2		35
#define TEGRA_IO_PAD_GROUP_UFS		36
#define TEGRA_IO_PAD_GROUP_AO_HV	37
#define TEGRA_IO_PAD_GROUP_DDR_DVI	38
#define TEGRA_IO_PAD_GROUP_DDR_GMI	39
#define TEGRA_IO_PAD_GROUP_DDR_SDMMC2	40
#define TEGRA_IO_PAD_GROUP_DDR_SPI	41

#define IO_PAD_VOLTAGE_1_2V	1200000
#define IO_PAD_VOLTAGE_1_8V	1800000
#define IO_PAD_VOLTAGE_3_3V	3300000

#endif
