obj-$(CONFIG_IGB_AVB) += igb_avb.o

igb_avb-y := igb_main.o \
	     e1000_82575.o \
	     e1000_i210.o \
	     e1000_mac.o \
	     e1000_nvm.o e1000_phy.o \
	     e1000_manage.o \
	     igb_param.o \
	     igb_ethtool.o \
	     kcompat.o \
	     e1000_api.o \
	     e1000_mbx.o \
	     igb_vmdq.o \
	     igb_procfs.o \
	     igb_hwmon.o \
	     igb_debugfs.o \
	     igb_ptp.o
