#
#  Copyright (c) 2010 - 2018 Intel Corporation.
#
#  This program is free software; you can redistribute it and/or modify it
#  under the terms and conditions of the GNU General Public License,
#  version 2, as published by the Free Software Foundation.
#
#  This program is distributed in the hope it will be useful, but WITHOUT
#  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
#  more details.
#

obj-$(CONFIG_VIDEO_INTEL_ICI)	+= ici/
ifndef CONFIG_VIDEO_INTEL_ICI
obj-$(CONFIG_VIDEO_INTEL_IPU4)	+= ipu4/
endif
obj-$(CONFIG_VIDEO_INTEL_IPU4P)	+= ipu4/
