#ifndef MAILBOX_SERVICE_SLOG_H
#define MAILBOX_SERVICE_SLOG_H

#define SLOG_SERVICE_CMD_GET_VERSION        0

#define SLOG_SERVICE_CMD_LOG_MESSAGE        1

#define SLOG_SERVICE_RSP_LOG_MESSAGE        (MBOX_COMMAND_RESPONSE_ID | SLOG_SERVICE_CMD_LOG_MESSAGE)

#define SLOG_SERVICE_CMD_RESET_LOG           4

#define SLOG_SERVICE_RSP_RESET_LOG           (MBOX_COMMAND_RESPONSE_ID | SLOG_SERVICE_CMD_RESET_LOG)

#endif

