#ifndef MAILBOX_SERVICE_OTP_H
#define MAILBOX_SERVICE_OTP_H

#define OTP_SERVICE_CMD_GET_VERSION                 0

#define OTP_SERVICE_CMD_GET_CHIP_ID                 1

#define OTP_SERVICE_CMD_GET_GENEALOGY_PCBA_VERSION  2

#define OTP_SERVICE_CMD_GET_GENEALOGY_PCBA_SERIAL  3

#define OTP_SERVICE_CMD_GET_GENEALOGY_TLA_VERSION  4

#define OTP_SERVICE_CMD_GET_GENEALOGY_TLA_SERIAL  5

#define OTP_SERVICE_CMD_GET_GENEALOGY_IS_DUK_BLANK  6

#define OTP_SERVICE_CMD_GET_GENEALOGY_IS_ROOT_CA_BLANK  7

#define OTP_SERVICE_CMD_GET_GENEALOGY_IS_COMM_CA_BLANK  8

#define OTP_SERVICE_CMD_GET_GENEALOGY_IS_DUK_LOCKED  9

#define OTP_SERVICE_CMD_GET_GENEALOGY_IS_ROOT_CA_LOCKED  10

#define OTP_SERVICE_CMD_GET_KEY_WRAPPED_FMP_KEY 11

#define OTP_SERVICE_CMD_IS_FMP_OTP_KEY_FORCE_BIT_FUSED 12

#define OTP_SERVICE_CMD_FUSE_FMP_OTP_KEY_FORCE_BIT 13

#define OTP_SERVICE_CMD_FUSE_FMP_KEY 14

#define OTP_SERVICE_CMD_GET_FMP_KEY_LOCK_BIT 15

#define OTP_SERVICE_CMD_FUSE_FMP_KEY_LOCK_BIT 16

#define OTP_SERVICE_CMD_GET_GENEALOGY_IS_JTAG_LOCKED 17

#define OTP_SERVICE_CMD_GET_GENEALOGY_IS_OTHER_SOC_FUSED 18

#define OTP_SERVICE_CMD_GET_MONOTONIC_COUNTER 21

#define OTP_MONOTONIC_COUNTER_CRL       0
#define OTP_MONOTONIC_COUNTER_BL1       1
#define OTP_MONOTONIC_COUNTER_BL2       2
#define OTP_MONOTONIC_COUNTER_SMS       3
#define OTP_MONOTONIC_COUNTER_A72       4
#define OTP_MONOTONIC_COUNTER_BOOTBLOCK 5
#define OTP_MONOTONIC_COUNTER_COREBOOT  6

#define OTP_SERVICE_CMD_FUSE_FACTORY_GATED 22

#define OTP_SERVICE_CMD_GET_FACTORY_GATED 23

#endif
