#ifndef MAILBOX_SERVICE_BOOT_H
#define MAILBOX_SERVICE_BOOT_H

#define BOOT_SERVICE_CMD_GET_VERSION    0

#define BOOT_SERVICE_CMD_GET_TURBO_ID   1

#define BOOT_SERVICE_CMD_GET_OTP_STATE   2

#define BOOT_SERVICE_CMD_GET_A72_STATE   3

#define BOOT_SERVICE_CMD_SET_AP_BOOTED_OS   20

#define BOOT_SERVICE_CMD_IS_RECOVERY_MODE   22

#define BOOT_SERVICE_CMD_IS_FORCED_RECOVERY_MODE_SET   23

#define BOOT_SERVICE_CMD_FORCED_RECOVERY_MODE_SET   24

#define BOOT_SERVICE_CMD_RECOVERY_MODE_CLEAR   25

#define BOOT_SERVICE_CMD_A72_COMPLETED_OK   27

#define BOOT_SERVICE_CMD_GET_SCSBL2_CRT_USAGE_RESTRICTIONS 30

#define BOOT_SERVICE_CMD_GET_SMS_CRT_USAGE_RESTRICTIONS 31

#define BOOT_SERVICE_CMD_GET_A72BL1_CRT_USAGE_RESTRICTIONS 32

#define BOOT_SERVICE_CMD_GET_BOOTBLOCK_CRT_USAGE_RESTRICTIONS 33

#define BOOT_SERVICE_CMD_GET_COREBOOT_CRT_USAGE_RESTRICTIONS 34

#define BOOT_SERVICE_CMD_FMP_SET_ENABLED 35

#define BOOT_SERVICE_CMD_FMP_GET_ENABLED 36

#define BOOT_SERVICE_CMD_BOOT_BANK_SWITCH   37

#define BOOT_SERVICE_CMD_GET_BL1_DATA_VER   38

#define BOOT_SERVICE_CMD_GET_NEED_RESET   39

#define BOOT_SERVICE_CMD_UNLOCK_TOKEN_CLEAR 40

#define BOOT_SERVICE_CMD_GET_FAILED_COUNT 41

#define BOOT_SERVICE_CMD_SET_FAILED_COUNT 42

#define BOOT_SERVICE_RSP_SET_FAILED_COUNT   (MBOX_COMMAND_RESPONSE_ID | BOOT_SERVICE_CMD_SET_FAILED_COUNT)

#endif
