#ifndef MAILBOX_SERVICES_H
#define MAILBOX_SERVICES_H

#define MAILBOX_SERVICE_ID_FILE 1
#define MAILBOX_SERVICE_ID_DCCM 2
#define MAILBOX_SERVICE_ID_PMIC 3
#define MAILBOX_SERVICE_ID_KEYS 4
#define MAILBOX_SERVICE_ID_OTP  5
#define MAILBOX_SERVICE_ID_SLOG 6
#define MAILBOX_SERVICE_ID_ELOG 7
#define MAILBOX_SERVICE_ID_BOOT 8
#define MAILBOX_SERVICE_ID_COMM 9
#define MAILBOX_SERVICE_ID_TMU  10
#define MAILBOX_SERVICE_ID_RECOVERY 11
#define MAILBOX_SERVICE_ID_SLEEP 12
#define MAILBOX_SERVICE_ID_ETHERNET 13
#define MAILBOX_SERVICE_ID_GPIO 14
#define MAILBOX_SERVICE_ID_PROVISIONING 15
#define MAILBOX_SERVICE_ID_AP 16
#define MAILBOX_SERVICE_ID_RTC 17

#endif
