#ifndef MAILBOX_SERVICE_PROVISIONING_H
#define MAILBOX_SERVICE_PROVISIONING_H

#define PROVISIONING_SERVICE_CMD_GET_VERSION                    0



#define PROVISIONING_SERVICE_CMD_SET_PCBA_VERSION               1

#define PROVISIONING_SERVICE_RSP_SET_PCBA_VERSION            (MBOX_COMMAND_RESPONSE_ID | PROVISIONING_SERVICE_CMD_SET_PCBA_VERSION)



#define PROVISIONING_SERVICE_CMD_SET_PCBA_SERIAL               2

#define PROVISIONING_SERVICE_RSP_SET_PCBA_SERIAL            (MBOX_COMMAND_RESPONSE_ID | PROVISIONING_SERVICE_CMD_SET_PCBA_SERIAL)



#define PROVISIONING_SERVICE_CMD_SET_TLA_VERSION               3

#define PROVISIONING_SERVICE_RSP_SET_TLA_VERSION            (MBOX_COMMAND_RESPONSE_ID | PROVISIONING_SERVICE_CMD_SET_TLA_VERSION)



#define PROVISIONING_SERVICE_CMD_SET_TLA_SERIAL               4

#define PROVISIONING_SERVICE_RSP_SET_TLA_SERIAL            (MBOX_COMMAND_RESPONSE_ID | PROVISIONING_SERVICE_CMD_SET_TLA_SERIAL)

#endif
