#ifndef MAILBOX_SERVICE_FILESYSTEM_H
#define MAILBOX_SERVICE_FILESYSTEM_H

#define FILE_SERVICE_CMD_GET_VERSION        0

#define FILE_SERVICE_CMD_GET_FILE_SIZE      1

#define FILE_SERVICE_CMD_GET_FILE           2

#define FILE_SERVICE_RSP_GET_FILE       (MBOX_COMMAND_RESPONSE_ID | FILE_SERVICE_CMD_GET_FILE)

#define FILE_SERVICE_CMD_UPDATE_FILE        3

#define FILE_SERVICE_RSP_UPDATE_FILE       (MBOX_COMMAND_RESPONSE_ID | FILE_SERVICE_CMD_UPDATE_FILE)

#define FILE_SERVICE_CMD_GET_COREBOOT_SIZE  4

#define FILE_SERVICE_CMD_LOAD_COREBOOT      5

#define FILE_SERVICE_RSP_LOAD_COREBOOT      (MBOX_COMMAND_RESPONSE_ID | FILE_SERVICE_CMD_LOAD_COREBOOT)

#define FILE_SERVICE_CMD_SWAP_COREBOOT      6

#define FILE_SERVICE_RSP_SWAP_COREBOOT      (MBOX_COMMAND_RESPONSE_ID | FILE_SERVICE_CMD_SWAP_COREBOOT)

#define FILE_SERVICE_CMD_GET_BOOTBLOCK_SIZE  7

#define FILE_SERVICE_CMD_LOAD_BOOTBLOCK      8

#define FILE_SERVICE_RSP_LOAD_BOOTBLOCK      (MBOX_COMMAND_RESPONSE_ID | FILE_SERVICE_CMD_LOAD_BOOTBLOCK)

#define FILE_SERVICE_CMD_UPDATE_FIRMWARE    9

#define FILE_SERVICE_RSP_UPDATE_FIRMWARE    (MBOX_COMMAND_RESPONSE_ID | FILE_SERVICE_CMD_UPDATE_FIRMWARE)

#define FILE_SERVICE_CMD_VERIFY_FILE    10

#define FILE_SERVICE_RSP_VERIFY_FILE    (MBOX_COMMAND_RESPONSE_ID | FILE_SERVICE_CMD_VERIFY_FILE)

#define FILE_SERVICE_FILE_ROOT_CA_ID            0x01
#define FILE_SERVICE_FILE_SCS_BL1_ID            0x02
#define FILE_SERVICE_FILE_CRL_ID                0x03
#define FILE_SERVICE_FILE_SCS_BL2_CRT_ID        0x10
#define FILE_SERVICE_FILE_SCS_BL2_ID            0x11
#define FILE_SERVICE_FILE_SMS_BL1_CRT_ID        0x20
#define FILE_SERVICE_FILE_SMS_BL1_ID            0x21

#define FILE_SERVICE_FILE_A72_BL1_CRT_ID        0x30
#define FILE_SERVICE_FILE_A72_BL1_ID            0x31
#define FILE_SERVICE_FILE_A72_COREBOOT_A_CRT_ID 0x32
#define FILE_SERVICE_FILE_A72_COREBOOT_A_ID     0x33
#define FILE_SERVICE_FILE_A72_COREBOOT_B_CRT_ID 0x34
#define FILE_SERVICE_FILE_A72_COREBOOT_B_ID     0x35
#define FILE_SERVICE_FILE_A72_CONFIG_ID         0x36
#define FILE_SERVICE_FILE_A72_BOOTBLOCK_A_CRT_ID 0x37
#define FILE_SERVICE_FILE_A72_BOOTBLOCK_A_ID     0x38
#define FILE_SERVICE_FILE_A72_BOOTBLOCK_B_CRT_ID 0x39
#define FILE_SERVICE_FILE_A72_BOOTBLOCK_B_ID     0x3A

#define FILE_SERVICE_FILE_SLOG_ID                0x3D

#endif
