/*
 * drivers/video/tegra/host/gm20b/gm20b_gating_reglist.h
 *
 * Copyright (c) 2014-2015, NVIDIA Corporation. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * This file is autogenerated.  Do not edit.
 */

#include "gk20a/gk20a.h"

void gm20b_slcg_bus_load_gating_prod(struct gk20a *g,
	bool prod);

void gm20b_slcg_ce2_load_gating_prod(struct gk20a *g,
	bool prod);

void gm20b_slcg_chiplet_load_gating_prod(struct gk20a *g,
	bool prod);

void gm20b_slcg_ctxsw_firmware_load_gating_prod(struct gk20a *g,
	bool prod);

void gm20b_slcg_fb_load_gating_prod(struct gk20a *g,
	bool prod);

void gm20b_slcg_fifo_load_gating_prod(struct gk20a *g,
	bool prod);

void gr_gm20b_slcg_gr_load_gating_prod(struct gk20a *g,
	bool prod);

void ltc_gm20b_slcg_ltc_load_gating_prod(struct gk20a *g,
	bool prod);

void gm20b_slcg_perf_load_gating_prod(struct gk20a *g,
	bool prod);

void gm20b_slcg_priring_load_gating_prod(struct gk20a *g,
	bool prod);

void gm20b_slcg_pwr_csb_load_gating_prod(struct gk20a *g,
	bool prod);

void gm20b_slcg_pmu_load_gating_prod(struct gk20a *g,
	bool prod);

void gm20b_slcg_therm_load_gating_prod(struct gk20a *g,
	bool prod);

void gm20b_slcg_xbar_load_gating_prod(struct gk20a *g,
	bool prod);

void gm20b_blcg_bus_load_gating_prod(struct gk20a *g,
	bool prod);

void gm20b_blcg_ctxsw_firmware_load_gating_prod(struct gk20a *g,
	bool prod);

void gm20b_blcg_fb_load_gating_prod(struct gk20a *g,
	bool prod);

void gm20b_blcg_fifo_load_gating_prod(struct gk20a *g,
	bool prod);

void gm20b_blcg_gr_load_gating_prod(struct gk20a *g,
	bool prod);

void gm20b_blcg_ltc_load_gating_prod(struct gk20a *g,
	bool prod);

void gm20b_blcg_pwr_csb_load_gating_prod(struct gk20a *g,
	bool prod);

void gm20b_blcg_pmu_load_gating_prod(struct gk20a *g,
	bool prod);

void gm20b_blcg_xbar_load_gating_prod(struct gk20a *g,
	bool prod);

void gr_gm20b_pg_gr_load_gating_prod(struct gk20a *g,
	bool prod);

