ccflags-y += -Werror
ccflags-y += -I$(srctree)/drivers/platform/tegra/mc

obj-$(CONFIG_ARCH_TEGRA_18x_SOC) += mcerr_ecc_t18x.o
obj-$(CONFIG_ARCH_TEGRA_18x_SOC) += mc_addr_translate.o
obj-$(CONFIG_ARCH_TEGRA_18x_SOC) += mc-sid.o
obj-$(CONFIG_ARCH_TEGRA_18x_SOC) += mcerr-t18x.o
obj-$(CONFIG_ARCH_TEGRA_18x_SOC) += tegra18_emc.o
obj-$(CONFIG_ARCH_TEGRA_18x_SOC) += bwmgr_mc_t186.o
obj-$(CONFIG_ARCH_TEGRA_18x_SOC) += tegra18x_la.o
