# 
#
# ISYS_INFOBITS
#

ISYS_INFOBITS_DIR = $(MODULES_DIR)/isys_infobits

ISYS_INFOBITS_INTERFACE = $(ISYS_INFOBITS_DIR)/interface
ISYS_INFOBITS_SOURCES = $(ISYS_INFOBITS_DIR)/src

ISYS_INFOBITS_CPPFLAGS := -I$(ISYS_INFOBITS_INTERFACE)

ISYS_INFOBITS_HOST_FILES = 	$(ISYS_INFOBITS_SOURCES)/isys_infobits.c

ISYS_INFOBITS_FW_FILES = $(ISYS_INFOBITS_HOST_FILES)

