# MODULE is CPD UTL (Metadata File Extension)

CPD_DIR  		= $${MODULES_DIR}/cpd/
CPD_METADATA_DIR	= $${MODULES_DIR}/cpd/cpd_metadata
CPD_METADATA_INTERFACE	= $(CPD_METADATA_DIR)/interface
CPD_METADATA_SOURCES	= $(CPD_METADATA_DIR)/src

CPD_METADATA_FILES	= $(CPD_METADATA_SOURCES)/ia_css_cpd_metadata_create.c
CPD_METADATA_FILES	+= $(CPD_METADATA_SOURCES)/ia_css_cpd_metadata.c
CPD_METADATA_CPPFLAGS	= -I$(CPD_METADATA_INTERFACE) \
			  -I$(CPD_METADATA_SOURCES) \
			  -I$(CPD_DIR)
