# 
#
# MODULE is SYSCOM

SYSCOM_DIR=$${MODULES_DIR}/syscom

SYSCOM_INTERFACE=$(SYSCOM_DIR)/interface
SYSCOM_SOURCES1=$(SYSCOM_DIR)/src

SYSCOM_HOST_FILES += $(SYSCOM_SOURCES1)/ia_css_syscom.c

SYSCOM_HOST_CPPFLAGS += -I$(SYSCOM_INTERFACE)
SYSCOM_HOST_CPPFLAGS += -I$${MODULES_DIR}/devices

SYSCOM_FW_FILES += $(SYSCOM_SOURCES1)/ia_css_syscom_fw.c

SYSCOM_FW_CPPFLAGS += -I$(SYSCOM_INTERFACE)
SYSCOM_FW_CPPFLAGS += -I$(SYSCOM_SOURCES1)
