obj-y += dc.o
obj-y += rgb.o
obj-y += hdmi.o
obj-y += nvhdcp.o
obj-y += edid.o
obj-y += nvsd.o
obj-y += dsi.o
obj-y += dc_sysfs.o
obj-$(CONFIG_TEGRA_OVERLAY) += overlay.o
obj-$(CONFIG_TEGRA_DC_EXTENSIONS) += ext/

include $(srctree)/compat26/Makefile.inc
