/*
 * Copyright (c) 2017 Samsung Electronics Co., Ltd.
 * Author: Shaik Ameer Basha <shaik.ameer@samsung.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
*/

#ifndef _DT_BINDINGS_CLOCK_TRAV_H
#define _DT_BINDINGS_CLOCK_TRAV_H

/* CMU */
#define DOUT_CMU_PLL_SHARED0_DIV4		1
#define DOUT_CMU_PERIC_SHARED1DIV36		2
#define DOUT_CMU_PERIC_SHARED0DIV3_TBUCLK	3
#define DOUT_CMU_PERIC_SHARED0DIV20		4
#define DOUT_CMU_PERIC_SHARED1DIV4_DMACLK	5
#define DOUT_CMU_PLL_SHARED0_DIV6		6
#define DOUT_CMU_FSYS0_SHARED1DIV4		7
#define DOUT_CMU_FSYS0_SHARED0DIV4		8
#define DOUT_CMU_FSYS1_SHARED0DIV8		9
#define DOUT_CMU_FSYS1_SHARED0DIV4		10
#define CMU_CPUCL_SWITCH_GATE			11
#define DOUT_CMU_IMEM_TCUCLK			12
#define DOUT_CMU_IMEM_ACLK			13
#define DOUT_CMU_IMEM_DMACLK			14
#define DOUT_CMU_ISP_TCUCLK			15
#define DOUT_CMU_GPU_MAIN_SWITCH		16
#define DOUT_CMU_DPRX_DSC_CLK			17
#define DOUT_CMU_DPRX_SWITCHCLK			18
#define GAT_CMU_FSYS0_SHARED0DIV4		19

#define CMU_NR_CLK				20

/* PERIC */
#define PERIC_SCLK_UART0			1
#define PERIC_PCLK_UART0			2
#define PERIC_SCLK_UART1			3
#define PERIC_PCLK_UART1			4
#define PERIC_DMA0_IPCLKPORT_ACLK		5
#define PERIC_DMA1_IPCLKPORT_ACLK		6
#define PERIC_PWM0_IPCLKPORT_I_PCLK_S0		7
#define PERIC_PWM1_IPCLKPORT_I_PCLK_S0		8
#define PERIC_PCLK_SPI0                         9
#define PERIC_SCLK_SPI0                         10
#define PERIC_PCLK_SPI1                         11
#define PERIC_SCLK_SPI1                         12
#define PERIC_PCLK_SPI2                         13
#define PERIC_SCLK_SPI2                         14
#define PERIC_PCLK_TDM0                         15
#define PERIC_PCLK_HSI2C0			16
#define PERIC_PCLK_HSI2C1			17
#define PERIC_PCLK_HSI2C2			18
#define PERIC_PCLK_HSI2C3			19
#define PERIC_PCLK_HSI2C4			20
#define PERIC_PCLK_HSI2C5			21
#define PERIC_PCLK_HSI2C6			22
#define PERIC_PCLK_HSI2C7			23
#define PERIC_MCAN0_IPCLKPORT_CCLK		24
#define PERIC_MCAN0_IPCLKPORT_PCLK		25
#define PERIC_MCAN1_IPCLKPORT_CCLK		26
#define PERIC_MCAN1_IPCLKPORT_PCLK		27
#define PERIC_MCAN2_IPCLKPORT_CCLK		28
#define PERIC_MCAN2_IPCLKPORT_PCLK		29
#define PERIC_MCAN3_IPCLKPORT_CCLK		30
#define PERIC_MCAN3_IPCLKPORT_PCLK		31
#define PERIC_PCLK_ADCIF			32
#define PERIC_EQOS_TOP_IPCLKPORT_CLK_PTP_REF_I  33
#define PERIC_EQOS_TOP_IPCLKPORT_ACLK_I		34
#define PERIC_EQOS_TOP_IPCLKPORT_HCLK_I		35
#define PERIC_EQOS_TOP_IPCLKPORT_RGMII_CLK_I	36
#define PERIC_EQOS_TOP_IPCLKPORT_CLK_RX_I	37
#define PERIC_BUS_D_PERIC_IPCLKPORT_EQOSCLK	38
#define PERIC_BUS_P_PERIC_IPCLKPORT_EQOSCLK	39
#define PERIC_HCLK_TDM0				40
#define PERIC_PCLK_TDM1				41
#define PERIC_HCLK_TDM1				42
#define PERIC_EQOS_PHYRXCLK_MUX		43
#define PERIC_EQOS_PHYRXCLK			44
#define PERIC_DOUT_RGMII_CLK		45

#define PERIC_NR_CLK				46

/* FSYS0 */
#define UFS0_MPHY_REFCLK_IXTAL24		1
#define UFS0_MPHY_REFCLK_IXTAL26		2
#define UFS1_MPHY_REFCLK_IXTAL24		3
#define UFS1_MPHY_REFCLK_IXTAL26		4
#define UFS0_TOP0_HCLK_BUS			5
#define UFS0_TOP0_ACLK				6
#define UFS0_TOP0_CLK_UNIPRO			7
#define UFS0_TOP0_FMP_CLK			8
#define UFS1_TOP1_HCLK_BUS			9
#define UFS1_TOP1_ACLK				10
#define UFS1_TOP1_CLK_UNIPRO			11
#define UFS1_TOP1_FMP_CLK			12
#define USB20DRD_IPCLKPORT_ACLK_BUS		13
#define USB20DRD_IPCLKPORT_ACLK_BUS_PHYCTRL	14
#define USB20DRD_IPCLKPORT_ACLK_PHYCTRL		15
#define USB20DRD_IPCLKPORT_BUS_CLK_EARLY	16
#define USB20DRD_IPCLKPORT_REF_CLK		17
#define USB20DRD_IPCLKPORT_USB20_CLKCORE_0	18
#define PCIE_SUBCTRL_INST0_DBI_ACLK_SOC		19
#define PCIE_SUBCTRL_INST0_AUX_CLK_SOC		20
#define PCIE_SUBCTRL_INST0_MSTR_ACLK_SOC	21
#define PCIE_SUBCTRL_INST0_SLV_ACLK_SOC		22
#define FSYS0_EQOS_TOP0_IPCLKPORT_CLK_PTP_REF_I 23
#define FSYS0_EQOS_TOP0_IPCLKPORT_ACLK_I	24
#define FSYS0_EQOS_TOP0_IPCLKPORT_HCLK_I	25
#define FSYS0_EQOS_TOP0_IPCLKPORT_RGMII_CLK_I	26
#define FSYS0_EQOS_TOP0_IPCLKPORT_CLK_RX_I	27

#define FSYS0_NR_CLK				28

/* FSYS1 */
#define PCIE_LINK0_IPCLKPORT_DBI_ACLK		1
#define PCIE_LINK0_IPCLKPORT_AUX_ACLK		2
#define PCIE_LINK0_IPCLKPORT_MSTR_ACLK		3
#define PCIE_LINK0_IPCLKPORT_SLV_ACLK		4
#define PCIE_LINK1_IPCLKPORT_DBI_ACLK		5
#define PCIE_LINK1_IPCLKPORT_AUX_ACLK		6
#define PCIE_LINK1_IPCLKPORT_MSTR_ACLK		7
#define PCIE_LINK1_IPCLKPORT_SLV_ACLK		8
#define FSYS1_NR_CLK				9

/* CORE_GT */
#define DOUT_CORE_GT_DIV_MIF_SWITCHCLK		1
#define CORE_GT_NR_CLK				2

/* CORE_MIFL */
#define MOUT_CORE_MIFL_PLL_MIFL_CLK		1
#define CORE_MIFL_NR_CLK			2

/* CORE_MIFR */
#define MOUT_CORE_MIFR_PLL_MIFR_CLK		1
#define CORE_MIFR_NR_CLK			2

/* CPUCL */
#define CLK_ARM_CLK				1
#define MOUT_CPUCL_PLL				2
#define CPUCL_CLUSTER_CLK_MUX			3
#define CPUCL_SWITCHCLK_MUX			4
#define CPUCL_NR_CLK				5

/* IMEM */
#define IMEM_DMA0_IPCLKPORT_ACLK		1
#define IMEM_DMA1_IPCLKPORT_ACLK		2
#define IMEM_WDT0_IPCLKPORT_PCLK		3
#define IMEM_WDT1_IPCLKPORT_PCLK		4
#define IMEM_WDT2_IPCLKPORT_PCLK		5
#define IMEM_MCT_PCLK				6
#define IMEM_TMU_CPU0_IPCLKPORT_I_CLK_TS	7
#define IMEM_TMU_CPU2_IPCLKPORT_I_CLK_TS	8
#define IMEM_TMU_GPU_IPCLKPORT_I_CLK_TS		9
#define IMEM_TMU_GT_IPCLKPORT_I_CLK_TS		10
#define IMEM_TMU_TOP_IPCLKPORT_I_CLK_TS		11
#define IMEM_NR_CLK				12

/* PMU */
#define PMU_NR_CLK				1

/* MIF0 */
#define MIF0_NR_CLK				1

/* MIF1 */
#define MIF1_NR_CLK				1

/* MIF2 */
#define MIF2_NR_CLK				1

/* MIF3 */
#define MIF3_NR_CLK				1

/* MIF4 */
#define MIF4_NR_CLK				1

/* MIF5 */
#define MIF5_NR_CLK				1

/* MIF6 */
#define MIF6_NR_CLK				1

/* MIF7 */
#define MIF7_NR_CLK				1

/* MFC */
#define MFC_MFC_IPCLKPORT_ACLK			1
#define MFC_NR_CLK				2

/* ISP */
#define ISP_NR_CLK				1

/* GPU */
#define MOUT_GPU_CLK_PLL			1
#define MOUT_GPU_CLK_GPU_BUSD			2
#define MOUT_GPU_CLK_SWITCH_USER		3
#define CLK_GPU_GPU_IPCLKPORT_CLK		4
#define GPU_NR_CLK				5

/* CAM_CSI */
#define CAM_CSI_NR_CLK				1

/* TRIP */
#define CLK_TRIP_CLK				1
#define MOUT_TRIP_PLL				2
#define MOUT_TRIP_SWITCH_MUX			3
#define MOUT_TRIP_SWITCH_PLL_MUX		4
#define TRIP_NR_CLK				5

/* CAM_DPRX0 */
#define MOUT_CAM_DPRX0_PLL			1
#define MOUT_CAM_DPRX0_SWITCH_MUX		2
#define DPRX2_IPCLKPORT_RXCLK			3
#define DPRX3_IPCLKPORT_RXCLK			4
#define DPRX2_IPCLKPORT_I_DSC_CLK		5
#define DPRX3_IPCLKPORT_I_DSC_CLK		6
#define APB_ASYNC_DPRX2_IPCLKPORT_PCLKM		7
#define APB_ASYNC_DPRX3_IPCLKPORT_PCLKM		8
#define APB_ASYNC_DPRX2_IPCLKPORT_PCLKS		9
#define APB_ASYNC_DPRX3_IPCLKPORT_PCLKS		10
#define DPRX2_IPCLKPORT_PCLK			11
#define DPRX3_IPCLKPORT_PCLK			12
#define BUS_P_CAM_DPRX_0_IPCLKPORT_MAINCLK_R	13
#define BUS_P_CAM_DPRX_0_IPCLKPORT_MAINCLK	14
#define SYSREG_CAM_DPRX0_IPCLKPORT_PCLK		15
#define AXI2APB_CAM_DPRX0_IPCLKPORT_ACLK	16
#define ADS_AXI_P_CAM_DPRX_IPCLKPORT_ACLKS	17
#define CAM_DPRX0_CMU_DPRX0_IPCLKPORT_PCLK	18
#define DPRX2_IPCLKPORT_ACLK			19
#define DPRX3_IPCLKPORT_ACLK			20
#define BUS_D_CAM_DPRX_0_IPCLKPORT_MAINCLK	21
#define TBU_CAM_DPRX_0_IPCLKPORT_ACLK		22
#define NS_BRDG_CAM_DPRX_0_IPCLKPORT_CLK__PSOC_CAM_DPRX__CLK_CAM_DPRX_D	23
#define NS_BRDG_CAM_DPRX_0_IPCLKPORT_CLK__PSOC_CAM_DPRX__CLK_CAM_DPRX_P	24
#define CAM_DPRX0_NR_CLK			25

/* CAM_DPRX1 */
#define DPRX0_IPCLKPORT_RXCLK			1
#define DPRX1_IPCLKPORT_RXCLK			2
#define DPRX0_IPCLKPORT_I_DSC_CLK		3
#define DPRX1_IPCLKPORT_I_DSC_CLK		4
#define APB_ASYNC_DPRX0_IPCLKPORT_PCLKM		5
#define APB_ASYNC_DPRX1_IPCLKPORT_PCLKM		6
#define APB_ASYNC_DPRX0_IPCLKPORT_PCLKS		7
#define APB_ASYNC_DPRX1_IPCLKPORT_PCLKS		8
#define DPRX0_IPCLKPORT_PCLK			9
#define DPRX1_IPCLKPORT_PCLK			10
#define BUS_P_CAM_DPRX_1_IPCLKPORT_MAINCLK_R	11
#define BUS_P_CAM_DPRX_1_IPCLKPORT_MAINCLK	12
#define SYSREG_CAM_DPRX1_IPCLKPORT_PCLK		13
#define AXI2APB_CAM_DPRX1_IPCLKPORT_ACLK	14
#define ADM_AXI_P_CAM_DPRX_IPCLKPORT_ACLKM	15
#define CAM_DPRX1_CMU_DPRX1_IPCLKPORT_PCLK	16
#define DPRX0_IPCLKPORT_ACLK			17
#define DPRX1_IPCLKPORT_ACLK			18
#define BUS_D_CAM_DPRX_1_IPCLKPORT_MAINCLK	19
#define TBU_CAM_DPRX_1_IPCLKPORT_ACLK		20
#define NS_BRDG_CAM_DPRX_1_IPCLKPORT_CLK__PSOC_CAM_DPRX1__CLK_CAM_DPRX_D	21
#define CAM_DPRX1_NR_CLK			22

#endif /* _DT_BINDINGS_CLOCK_TRAV_H */
