#ifndef MAILBOX_SERVICE_PMIC_H
#define MAILBOX_SERVICE_PMIC_H

#define PMIC_SERVICE_CMD_GET_VERSION        0

#define PMIC_SERVICE_CMD_POWER_SET        1

#define PMIC_SERVICE_RSP_POWER_SET        (MBOX_COMMAND_RESPONSE_ID | PMIC_SERVICE_CMD_POWER_SET)

#define PMIC_SERVICE_CMD_POWER_GET        2

#define PMIC_SERVICE_RSP_POWER_GET        (MBOX_COMMAND_RESPONSE_ID | PMIC_SERVICE_CMD_POWER_GET)

#define PMIC_SERVICE_POWER_12V0_SW          0x01
#define PMIC_SERVICE_POWER_INT              0x02
#define PMIC_SERVICE_POWER_CPU              0x03
#define PMIC_SERVICE_POWER_GPU              0x04
#define PMIC_SERVICE_POWER_TRIP0            0x05
#define PMIC_SERVICE_POWER_TRIP1            0x06
#define PMIC_SERVICE_POWER_1V8_DDR          0x07
#define PMIC_SERVICE_POWER_1V1_DDR          0x08
#define PMIC_SERVICE_POWER_IO_0V9           0x09
#define PMIC_SERVICE_POWER_IO_1V8           0x0A
#define PMIC_SERVICE_POWER_IO_3V3           0x0B
#define PMIC_SERVICE_POWER_IO_1V2           0x0C

#define PMIC_SERVICE_CMD_VOLTAGE_SET        3

#define PMIC_SERVICE_RSP_VOLTAGE_SET        (MBOX_COMMAND_RESPONSE_ID | PMIC_SERVICE_CMD_VOLTAGE_SET)

#define PMIC_SERVICE_CMD_VOLTAGE_GET        4

#define PMIC_SERVICE_RSP_VOLTAGE_GET        (MBOX_COMMAND_RESPONSE_ID | PMIC_SERVICE_CMD_VOLTAGE_GET)

#define PMIC_SERVICE_VOLTAGE_TURBO_INT      0x00000001
#define PMIC_SERVICE_VOLTAGE_TURBO_CPU      0x00000002
#define PMIC_SERVICE_VOLTAGE_TURBO_GPU      0x00000003
#define PMIC_SERVICE_VOLTAGE_TURBO_TRIP0    0x00000004
#define PMIC_SERVICE_VOLTAGE_TURBO_TRIP1    0x00000005

#define PMIC_SERVICE_CMD_A72_RESET          5

#define PMIC_SERVICE_RSP_A72_RESET       (MBOX_COMMAND_RESPONSE_ID | PMIC_SERVICE_CMD_A72_RESET)

#define PMIC_SERVICE_CMD_A72_POWER_OFF      6

#define PMIC_SERVICE_RSP_A72_POWER_OFF       (MBOX_COMMAND_RESPONSE_ID | PMIC_SERVICE_CMD_A72_POWER_OFF)

#define PMIC_SERVICE_CMD_A72_POWER_ON      7

#define PMIC_SERVICE_RSP_A72_POWER_ON       (MBOX_COMMAND_RESPONSE_ID | PMIC_SERVICE_CMD_A72_POWER_ON)

#define PMIC_SERVICE_CMD_PMIC_RESET      8

#define PMIC_SERVICE_RSP_PMIC_RESET       (MBOX_COMMAND_RESPONSE_ID | PMIC_SERVICE_CMD_PMIC_RESET)

#define PMIC_SERVICE_CMD_GET_HPM_ASV        9

#define PMIC_SERVICE_CMD_MEASURED_VOLTAGE_CURRENT_GET        10

#define PMIC_SERVICE_RSP_MEASURED_VOLTAGE_CURRENT_GET   (MBOX_COMMAND_RESPONSE_ID | PMIC_SERVICE_CMD_MEASURED_VOLTAGE_CURRENT_GET)

#define PMIC_SERVICE_MEASURED_VOLTAGE_TURBO_INT      0x00000001
#define PMIC_SERVICE_MEASURED_VOLTAGE_TURBO_CPU      0x00000002
#define PMIC_SERVICE_MEASURED_VOLTAGE_TURBO_TRIP0    0x00000003
#define PMIC_SERVICE_MEASURED_VOLTAGE_TURBO_TRIP1    0x00000004
#define PMIC_SERVICE_MEASURED_CURRENT_TURBO_INT      0x00000005
#define PMIC_SERVICE_MEASURED_CURRENT_TURBO_CPU      0x00000006
#define PMIC_SERVICE_MEASURED_CURRENT_TURBO_TRIP0    0x00000007
#define PMIC_SERVICE_MEASURED_CURRENT_TURBO_TRIP1    0x00000008

#define PMIC_SERVICE_CMD_TEMPERATURE_GET    11

#define PMIC_SERVICE_RSP_TEMPERATURE_GET    (MBOX_COMMAND_RESPONSE_ID | PMIC_SERVICE_CMD_TEMPERATURE_GET)

#define PMIC_SERVICE_TEMPERATURE_SENSOR_ID_0x48     0x00000001
#define PMIC_SERVICE_TEMPERATURE_SENSOR_ID_0x49     0x00000002
#define PMIC_SERVICE_TEMPERATURE_SENSOR_ID_0x4A     0x00000003
#define PMIC_SERVICE_TEMPERATURE_SENSOR_ID_0x4C     0x00000004

#endif
