#ifndef MAILBOX_SERVICE_COMM_H
#define MAILBOX_SERVICE_COMM_H

#define COMM_SERVICE_CMD_GET_VERSION		0

#define COMM_SERVICE_CMD_SET_COMM_REGION	1

#define COMM_SERVICE_CAN_REGION_ID		0
#define COMM_SERVICE_GP_REGION_ID		1

#endif
