#ifndef MAILBOX_SERVICE_TMU_H
#define MAILBOX_SERVICE_TMU_H

#define TMU_SERVICE_CMD_START_TRACE			0

#define TMU_SERVICE_CMD_STOP_TRACE			1

#define TMU_SERVICE_CMD_SET_SAMPLE_RATE     2

#define TMU_SERVICE_CMD_PRINT_TRACE         3

#define TMU_SERVICE_CMD_GET_CURRENT_TEMPS   4

#define TMU_SERVICE_CMD_GET_TRACE_SAMPLES   5


#endif
