#ifndef MAILBOX_SERVICE_AP_H
#define MAILBOX_SERVICE_AP_H

#define AP_SERVICE_CMD_GET_VERSION			0U

#define AP_SERVICE_CMD_GET_TURBO_ID         1U

#define AP_SERVICE_REDUNDANCY_STATUS_NOT_OK 0U
#define AP_SERVICE_REDUNDANCY_STATUS_OK 1U
#define AP_SERVICE_CMD_GET_REDUNDANCY_STATUS 2U

#define AP_SERVICE_CMD_REDUNDANCY_STATUS_UPDATE 3U

#define AP_SERVICE_AP_STATUS_NOT_OK 0U
#define AP_SERVICE_AP_STATUS_OK 1U
#define AP_SERVICE_CMD_GET_AP_STATUS 4U

#define AP_SERVICE_CMD_AP_STATUS_UPDATE 5U

#define AP_SERVICE_CMD_GET_FAULTED 6U

#define AP_SERVICE_ARB_STATE_INIT 0U
#define AP_SERVICE_ARB_STATE_IDLE 1U
#define AP_SERVICE_ARB_STATE_PRIMARY 2U
#define AP_SERVICE_ARB_STATE_SECONDARY 3U
#define AP_SERVICE_ARB_STATE_FAULT 4U
#define AP_SERVICE_ARB_STATE_MIA 5U
#define AP_SERVICE_ARB_STATE_UNKNOWN 6U
#define AP_SERVICE_CMD_GET_ARB_STATE 7U

#define AP_SERVICE_CMD_ARB_STATE_STATUS_UPDATE 8U

#define AP_SERVICE_NOT_OK_TO_START_AP_SESSION 0U
#define AP_SERVICE_OK_TO_START_AP_SESSION 1U
#define AP_SERVICE_CMD_GET_OK_TO_START_AP_SESSION 9U

#define AP_SERVICE_CMD_OK_TO_START_AP_SESSION_STATUS_UPDATE 10U

#define AP_SERVICE_CMD_GET_OTHER_SMS_HEALTH 11U
#define AP_SERVICE_CMD_OTHER_SMS_HEALTH_UPDATE 12U

#define AP_SERVICE_CMD_GET_OTHER_FAULT_STATE 13U
#define AP_SERVICE_CMD_OTHER_FAULT_STATE_UPDATE 14U

#endif
