#
# (C) COPYRIGHT 2012 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# A copy of the licence is included with the program, and can also be obtained
# from Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA  02110-1301, USA.
#
#

MALI_CUSTOMER_RELEASE = 1

platform_name := $(shell echo $(CONFIG_MALI_PLATFORM_NAME))

mali_kbase-y += \
	$(MALI_PLATFORM_DIR)/gpu_integration_callbacks.o \
	$(MALI_PLATFORM_DIR)/mali_kbase_platform.o \
	$(MALI_PLATFORM_DIR)/gpu_notifier.o \
	$(MALI_PLATFORM_DIR)/gpu_$(platform_name).o \
	$(MALI_PLATFORM_DIR)/gpu_control.o \
	$(MALI_PLATFORM_DIR)/gpu_pmqos.o \
	$(MALI_PLATFORM_DIR)/gpu_utilization.o \
	$(MALI_PLATFORM_DIR)/gpu_dvfs_handler.o \
	$(MALI_PLATFORM_DIR)/gpu_dvfs_api.o \
	$(MALI_PLATFORM_DIR)/gpu_dvfs_governor.o \
	$(MALI_PLATFORM_DIR)/gpu_perf.o
