GCOV_PROFILE := y

subdir-ccflags-y += -Werror

################################################################################
# tegra platform drivers
obj-$(CONFIG_ARCH_TEGRA_18x_SOC)		+= tegra_cpufreq.o
obj-$(CONFIG_ARCH_TEGRA_18x_SOC)		+= tegra_cluster_clk.o
################################################################################
