// SPDX-License_Identifier: GPL-2.0
// Copyright (C) 2015 - 2018 Intel Corporation

#include <linux/kernel.h>
#include "ipu-resources.h"

/*
 * Cell types by cell IDs
 */

const u32 ipu_fw_psys_cell_types[IPU_FW_PSYS_N_CELL_ID] = {
	IPU_FW_PSYS_SP_CTRL_TYPE_ID,
	IPU_FW_PSYS_SP_SERVER_TYPE_ID,
	IPU_FW_PSYS_SP_SERVER_TYPE_ID,
	IPU_FW_PSYS_VP_TYPE_ID,
	IPU_FW_PSYS_VP_TYPE_ID,
	IPU_FW_PSYS_VP_TYPE_ID,
	IPU_FW_PSYS_VP_TYPE_ID,
	IPU_FW_PSYS_ACC_ISA_TYPE_ID,
	IPU_FW_PSYS_ACC_PSA_TYPE_ID,
	IPU_FW_PSYS_ACC_PSA_TYPE_ID,
	IPU_FW_PSYS_ACC_PSA_TYPE_ID,
	IPU_FW_PSYS_ACC_PSA_TYPE_ID,
	IPU_FW_PSYS_ACC_PSA_TYPE_ID,
	IPU_FW_PSYS_ACC_PSA_TYPE_ID,
	IPU_FW_PSYS_ACC_OSA_TYPE_ID,
	IPU_FW_PSYS_GDC_TYPE_ID,
	IPU_FW_PSYS_GDC_TYPE_ID
};

const u16 ipu_num_dev_channels[IPU_FW_PSYS_N_DEV_CHN_ID] = {
	IPU_FW_PSYS_DEV_CHN_DMA_EXT0_MAX_SIZE,
	IPU_FW_PSYS_DEV_CHN_GDC_MAX_SIZE,
	IPU_FW_PSYS_DEV_CHN_DMA_EXT1_READ_MAX_SIZE,
	IPU_FW_PSYS_DEV_CHN_DMA_EXT1_WRITE_MAX_SIZE,
	IPU_FW_PSYS_DEV_CHN_DMA_INTERNAL_MAX_SIZE,
	IPU_FW_PSYS_DEV_CHN_DMA_IPFD_MAX_SIZE,
	IPU_FW_PSYS_DEV_CHN_DMA_ISA_MAX_SIZE,
	IPU_FW_PSYS_DEV_CHN_DMA_FW_MAX_SIZE,
#ifdef CONFIG_VIDEO_INTEL_IPU4P
	IPU_FW_PSYS_DEV_CHN_DMA_CMPRS_MAX_SIZE
#endif
};

const u16 ipu_fw_psys_mem_size[IPU_FW_PSYS_N_MEM_ID] = {
	IPU_FW_PSYS_VMEM0_MAX_SIZE,
	IPU_FW_PSYS_VMEM1_MAX_SIZE,
	IPU_FW_PSYS_VMEM2_MAX_SIZE,
	IPU_FW_PSYS_VMEM3_MAX_SIZE,
	IPU_FW_PSYS_VMEM4_MAX_SIZE,
	IPU_FW_PSYS_BAMEM0_MAX_SIZE,
	IPU_FW_PSYS_BAMEM1_MAX_SIZE,
	IPU_FW_PSYS_BAMEM2_MAX_SIZE,
	IPU_FW_PSYS_BAMEM3_MAX_SIZE,
	IPU_FW_PSYS_DMEM0_MAX_SIZE,
	IPU_FW_PSYS_DMEM1_MAX_SIZE,
	IPU_FW_PSYS_DMEM2_MAX_SIZE,
	IPU_FW_PSYS_DMEM3_MAX_SIZE,
	IPU_FW_PSYS_DMEM4_MAX_SIZE,
	IPU_FW_PSYS_DMEM5_MAX_SIZE,
	IPU_FW_PSYS_DMEM6_MAX_SIZE,
	IPU_FW_PSYS_DMEM7_MAX_SIZE,
	IPU_FW_PSYS_PMEM0_MAX_SIZE,
	IPU_FW_PSYS_PMEM1_MAX_SIZE,
	IPU_FW_PSYS_PMEM2_MAX_SIZE,
	IPU_FW_PSYS_PMEM3_MAX_SIZE
};

const enum ipu_mem_id
ipu_fw_psys_cell_mem[IPU_FW_PSYS_N_CELL_ID][IPU_FW_PSYS_N_DATA_MEM_TYPE_ID] = {
	{
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_DMEM0_ID,
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID
	},
	{
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_DMEM1_ID,
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID
	},
	{
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_DMEM2_ID,
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID
	},
	{
	 IPU_FW_PSYS_VMEM4_ID,
	 IPU_FW_PSYS_DMEM4_ID,
	 IPU_FW_PSYS_VMEM0_ID,
	 IPU_FW_PSYS_BAMEM0_ID
	},
	{
	 IPU_FW_PSYS_VMEM4_ID,
	 IPU_FW_PSYS_DMEM5_ID,
	 IPU_FW_PSYS_VMEM1_ID,
	 IPU_FW_PSYS_BAMEM1_ID
	},
	{
	 IPU_FW_PSYS_VMEM4_ID,
	 IPU_FW_PSYS_DMEM6_ID,
	 IPU_FW_PSYS_VMEM2_ID,
	 IPU_FW_PSYS_BAMEM2_ID
	},
	{
	 IPU_FW_PSYS_VMEM4_ID,
	 IPU_FW_PSYS_DMEM7_ID,
	 IPU_FW_PSYS_VMEM3_ID,
	 IPU_FW_PSYS_BAMEM3_ID
	},
	{
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID
	},
	{
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID
	},
	{
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID
	},
	{
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID
	},
	{
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID
	},
	{
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID
	},
	{
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID
	},
	{
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID
	},
	{
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID
	},
	{
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID,
	 IPU_FW_PSYS_N_MEM_ID
	}
};
