IPU_STEP = bxtB0
ccflags-y += -DIPU_STEP_BXTB0
include $(srctree)/$(src)/../Makefile.common
include $(srctree)/$(src)/../Makefile.lib2600
include $(srctree)/$(src)/../Makefile.lib2600psys
ccflags-y += -I$(srctree)/include/
ccflags-y += -I$(srctree)/$(src)/../
ccflags-y += -DPARAMETER_INTERFACE_V2
