# 
#
# PSYS_INFOBITS
#

PSYS_INFOBITS_DIR = $${MODULES_DIR}/psys_infobits

PSYS_INFOBITS_INTERFACE = $(PSYS_INFOBITS_DIR)/interface
PSYS_INFOBITS_SOURCES = $(PSYS_INFOBITS_DIR)/src

PSYS_INFOBITS_CPPFLAGS := \
		-I$(PSYS_INFOBITS_INTERFACE)

PSYS_INFOBITS_HOST_FILES = \
	$(PSYS_INFOBITS_SOURCES)/psys_infobits.c

PSYS_INFOBITS_FW_FILES = $(PSYS_INFOBITS_HOST_FILES)

