/*
* Support for Intel Camera Imaging ISP subsystem.
* Copyright (c) 2010 - 2015, Intel Corporation.
* 
* This program is free software; you can redistribute it and/or modify it
* under the terms and conditions of the GNU General Public License,
* version 2, as published by the Free Software Foundation.
* 
* This program is distributed in the hope it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
* more details.
*/
// generated file from <device>_reg_descr.hsd by hive_crgen.pl
#ifndef _ff_gbl_ccbcr_h
#define _ff_gbl_ccbcr_h


#define  FF_GBL_DFD_DATA_READ_CMD_ADDR  0x00c44
#define  FF_GBL_DFD_DATA_READ_COMPLETION_ADDR  0x00c40
#define  FF_GBL_DFD_EN_ADDR  0x00c30
#define  FF_GBL_DFD_SINGLE_STEP_ADDR  0x00c34
#define  FF_GBL_DFD_TRACED_DATA_ADDR  0x00c38
#define  FF_GBL_DFD_TRACED_DATA_VALID_ADDR  0x00c3c
#define  FF_GBL_GRD_CFG0_ADDR  0x00c00
#define  FF_GBL_GRD_CFG1_ADDR  0x00c04
#define  FF_GBL_GRD_CFG2_ADDR  0x00c08
#define  FF_GLOBAL_BL_BIAS_0_ADDR  0x00c0c
#define  FF_GLOBAL_BL_BIAS_1_ADDR  0x00c10
#define  FF_GLOBAL_BL_BIAS_2_ADDR  0x00c14
#define  FF_GLOBAL_BL_BIAS_3_ADDR  0x00c18
#define  FF_GLOBAL_BL_BIAS_4_ADDR  0x00c1c
#define  FF_GLOBAL_BL_BIAS_5_ADDR  0x00c20
#define  FF_GLOBAL_BL_BIAS_6_ADDR  0x00c24
#define  FF_GLOBAL_BL_BIAS_7_ADDR  0x00c28
#define  FF_GBL_HW_ASSR_CLEAR_ADDR  0x00c48
#define  FF_GBL_HW_ASSR_MASK_ADDR  0x00c4c
#define  FF_GBL_HW_ASSR_RAW_STAT_ADDR  0x00c54
#define  FF_GBL_HW_ASSR_STAT_ADDR  0x00c50
#define  FF_GBL_PWR_FEATURE_ADDR  0x00c2c



#define  MEM_BANK_FF_GBL_LUT_CH0_BASE_REG_ID    0 
#define  MEM_LUT_CH0_SET0_BASE_REG_IDX  0 
#define  MEM_LUT_CH0_SET0_LIMIT_REG_IDX  63 
#define  MEM_LUT_CH0_SET0_BASE_ADDR   0x00000 
#define  MEM_LUT_CH0_SET0_LIMIT_ADDR   0x000fc 
#define  MEM_LUT_CH0_SET1_BASE_REG_IDX  64 
#define  MEM_LUT_CH0_SET1_LIMIT_REG_IDX  127 
#define  MEM_LUT_CH0_SET1_BASE_ADDR   0x00100 
#define  MEM_LUT_CH0_SET1_LIMIT_ADDR   0x001fc 
#define  MEM_LUT_CH0_SET2_BASE_REG_IDX  128 
#define  MEM_LUT_CH0_SET2_LIMIT_REG_IDX  191 
#define  MEM_LUT_CH0_SET2_BASE_ADDR   0x00200 
#define  MEM_LUT_CH0_SET2_LIMIT_ADDR   0x002fc 
#define  MEM_BANK_FF_GBL_LUT_CH1_BASE_REG_ID    192 
#define  MEM_LUT_CH1_SET0_BASE_REG_IDX  192 
#define  MEM_LUT_CH1_SET0_LIMIT_REG_IDX  255 
#define  MEM_LUT_CH1_SET0_BASE_ADDR   0x00300 
#define  MEM_LUT_CH1_SET0_LIMIT_ADDR   0x003fc 
#define  MEM_LUT_CH1_SET1_BASE_REG_IDX  256 
#define  MEM_LUT_CH1_SET1_LIMIT_REG_IDX  319 
#define  MEM_LUT_CH1_SET1_BASE_ADDR   0x00400 
#define  MEM_LUT_CH1_SET1_LIMIT_ADDR   0x004fc 
#define  MEM_LUT_CH1_SET2_BASE_REG_IDX  320 
#define  MEM_LUT_CH1_SET2_LIMIT_REG_IDX  383 
#define  MEM_LUT_CH1_SET2_BASE_ADDR   0x00500 
#define  MEM_LUT_CH1_SET2_LIMIT_ADDR   0x005fc 
#define  MEM_BANK_FF_GBL_LUT_CH2_BASE_REG_ID    384 
#define  MEM_LUT_CH2_SET0_BASE_REG_IDX  384 
#define  MEM_LUT_CH2_SET0_LIMIT_REG_IDX  447 
#define  MEM_LUT_CH2_SET0_BASE_ADDR   0x00600 
#define  MEM_LUT_CH2_SET0_LIMIT_ADDR   0x006fc 
#define  MEM_LUT_CH2_SET1_BASE_REG_IDX  448 
#define  MEM_LUT_CH2_SET1_LIMIT_REG_IDX  511 
#define  MEM_LUT_CH2_SET1_BASE_ADDR   0x00700 
#define  MEM_LUT_CH2_SET1_LIMIT_ADDR   0x007fc 
#define  MEM_LUT_CH2_SET2_BASE_REG_IDX  512 
#define  MEM_LUT_CH2_SET2_LIMIT_REG_IDX  575 
#define  MEM_LUT_CH2_SET2_BASE_ADDR   0x00800 
#define  MEM_LUT_CH2_SET2_LIMIT_ADDR   0x008fc 
#define  MEM_BANK_FF_GBL_LUT_CH3_BASE_REG_ID    576 
#define  MEM_LUT_CH3_SET0_BASE_REG_IDX  576 
#define  MEM_LUT_CH3_SET0_LIMIT_REG_IDX  639 
#define  MEM_LUT_CH3_SET0_BASE_ADDR   0x00900 
#define  MEM_LUT_CH3_SET0_LIMIT_ADDR   0x009fc 
#define  MEM_LUT_CH3_SET1_BASE_REG_IDX  640 
#define  MEM_LUT_CH3_SET1_LIMIT_REG_IDX  703 
#define  MEM_LUT_CH3_SET1_BASE_ADDR   0x00a00 
#define  MEM_LUT_CH3_SET1_LIMIT_ADDR   0x00afc 
#define  MEM_LUT_CH3_SET2_BASE_REG_IDX  704 
#define  MEM_LUT_CH3_SET2_LIMIT_REG_IDX  767 
#define  MEM_LUT_CH3_SET2_BASE_ADDR   0x00b00 
#define  MEM_LUT_CH3_SET2_LIMIT_ADDR   0x00bfc 



#define FF_GBL_CCBCR_PARAM \
CONSTANT  FF_GBL_GRD_CFG0_REG_ID    : INTEGER := 0 ; \
CONSTANT  FF_GBL_GRD_CFG1_REG_ID    : INTEGER := 1 ; \
CONSTANT  FF_GBL_GRD_CFG2_REG_ID    : INTEGER := 2 ; \
CONSTANT  FF_GLOBAL_BL_BIAS_0_REG_ID    : INTEGER := 3 ; \
CONSTANT  FF_GLOBAL_BL_BIAS_1_REG_ID    : INTEGER := 4 ; \
CONSTANT  FF_GLOBAL_BL_BIAS_2_REG_ID    : INTEGER := 5 ; \
CONSTANT  FF_GLOBAL_BL_BIAS_3_REG_ID    : INTEGER := 6 ; \
CONSTANT  FF_GLOBAL_BL_BIAS_4_REG_ID    : INTEGER := 7 ; \
CONSTANT  FF_GLOBAL_BL_BIAS_5_REG_ID    : INTEGER := 8 ; \
CONSTANT  FF_GLOBAL_BL_BIAS_6_REG_ID    : INTEGER := 9 ; \
CONSTANT  FF_GLOBAL_BL_BIAS_7_REG_ID    : INTEGER := 10 ; \
CONSTANT  PWR_FEATURE_REG_ID    : INTEGER := 11 ; \
CONSTANT  DFD_EN_REG_ID    : INTEGER := 12 ; \
CONSTANT  DFD_SINGLE_STEP_REG_ID    : INTEGER := 13 ; \
CONSTANT  DFD_TRACED_DATA_REG_ID    : INTEGER := 14 ; \
CONSTANT  DFD_TRACED_DATA_VALID_REG_ID    : INTEGER := 15 ; \
CONSTANT  DFD_DATA_READ_COMPLETION_REG_ID    : INTEGER := 16 ; \
CONSTANT  DFD_DATA_READ_CMD_REG_ID    : INTEGER := 17 ; \
CONSTANT  HW_ASSR_CLEAR_REG_ID    : INTEGER := 18 ; \
CONSTANT  HW_ASSR_MASK_REG_ID    : INTEGER := 19 ; \
CONSTANT  HW_ASSR_STAT_REG_ID    : INTEGER := 20 ; \
CONSTANT  HW_ASSR_RAW_STAT_REG_ID    : INTEGER := 21 ; \
\
CONSTANT  DFD_DATA_READ_CMD_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  DFD_DATA_READ_COMPLETION_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  DFD_EN_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  DFD_SINGLE_STEP_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  DFD_TRACED_DATA_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  DFD_TRACED_DATA_VALID_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  FF_GBL_GRD_CFG0_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  FF_GBL_GRD_CFG1_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  FF_GBL_GRD_CFG2_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  FF_GLOBAL_BL_BIAS_0_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  FF_GLOBAL_BL_BIAS_1_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  FF_GLOBAL_BL_BIAS_2_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  FF_GLOBAL_BL_BIAS_3_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  FF_GLOBAL_BL_BIAS_4_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  FF_GLOBAL_BL_BIAS_5_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  FF_GLOBAL_BL_BIAS_6_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  FF_GLOBAL_BL_BIAS_7_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  HW_ASSR_CLEAR_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  HW_ASSR_MASK_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  HW_ASSR_RAW_STAT_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  HW_ASSR_STAT_REG_WIDTH    : INTEGER := 32 ; \
CONSTANT  PWR_FEATURE_REG_WIDTH    : INTEGER := 32 ; \
\
CONSTANT  DFD_DATA_READ_CMD_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  DFD_DATA_READ_COMPLETION_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  DFD_EN_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  DFD_SINGLE_STEP_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  DFD_TRACED_DATA_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  DFD_TRACED_DATA_VALID_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  FF_GBL_GRD_CFG0_REG_RSTVAL    : NATURAL := 20121608 ; \
CONSTANT  FF_GBL_GRD_CFG1_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  FF_GBL_GRD_CFG2_REG_RSTVAL    : NATURAL := 67328 ; \
CONSTANT  FF_GLOBAL_BL_BIAS_0_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  FF_GLOBAL_BL_BIAS_1_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  FF_GLOBAL_BL_BIAS_2_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  FF_GLOBAL_BL_BIAS_3_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  FF_GLOBAL_BL_BIAS_4_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  FF_GLOBAL_BL_BIAS_5_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  FF_GLOBAL_BL_BIAS_6_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  FF_GLOBAL_BL_BIAS_7_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  HW_ASSR_CLEAR_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  HW_ASSR_MASK_REG_RSTVAL    : NATURAL := 15 ; \
CONSTANT  HW_ASSR_RAW_STAT_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  HW_ASSR_STAT_REG_RSTVAL    : NATURAL := 0 ; \
CONSTANT  PWR_FEATURE_REG_RSTVAL    : NATURAL := 0 ; \
\
CONSTANT  FF_GBL_NOF_REGS : NATURAL := 790 ; \
CONSTANT  FF_GBL_NOF_REGS_BANK : NATURAL := 22 ; \
CONSTANT  c_num_of_regs : NATURAL := 790 ; \
CONSTANT  c_num_of_regs_bank : NATURAL :=  22; \
\
\
CONSTANT p_data_width                             : D1<INTEGER>; \
p_data_width{DFD_DATA_READ_CMD_REG_ID} := DFD_DATA_READ_CMD_REG_WIDTH   ; \
p_data_width{DFD_DATA_READ_COMPLETION_REG_ID} := DFD_DATA_READ_COMPLETION_REG_WIDTH   ; \
p_data_width{DFD_EN_REG_ID} := DFD_EN_REG_WIDTH   ; \
p_data_width{DFD_SINGLE_STEP_REG_ID} := DFD_SINGLE_STEP_REG_WIDTH   ; \
p_data_width{DFD_TRACED_DATA_REG_ID} := DFD_TRACED_DATA_REG_WIDTH   ; \
p_data_width{DFD_TRACED_DATA_VALID_REG_ID} := DFD_TRACED_DATA_VALID_REG_WIDTH   ; \
p_data_width{FF_GBL_GRD_CFG0_REG_ID} := FF_GBL_GRD_CFG0_REG_WIDTH   ; \
p_data_width{FF_GBL_GRD_CFG1_REG_ID} := FF_GBL_GRD_CFG1_REG_WIDTH   ; \
p_data_width{FF_GBL_GRD_CFG2_REG_ID} := FF_GBL_GRD_CFG2_REG_WIDTH   ; \
p_data_width{FF_GLOBAL_BL_BIAS_0_REG_ID} := FF_GLOBAL_BL_BIAS_0_REG_WIDTH   ; \
p_data_width{FF_GLOBAL_BL_BIAS_1_REG_ID} := FF_GLOBAL_BL_BIAS_1_REG_WIDTH   ; \
p_data_width{FF_GLOBAL_BL_BIAS_2_REG_ID} := FF_GLOBAL_BL_BIAS_2_REG_WIDTH   ; \
p_data_width{FF_GLOBAL_BL_BIAS_3_REG_ID} := FF_GLOBAL_BL_BIAS_3_REG_WIDTH   ; \
p_data_width{FF_GLOBAL_BL_BIAS_4_REG_ID} := FF_GLOBAL_BL_BIAS_4_REG_WIDTH   ; \
p_data_width{FF_GLOBAL_BL_BIAS_5_REG_ID} := FF_GLOBAL_BL_BIAS_5_REG_WIDTH   ; \
p_data_width{FF_GLOBAL_BL_BIAS_6_REG_ID} := FF_GLOBAL_BL_BIAS_6_REG_WIDTH   ; \
p_data_width{FF_GLOBAL_BL_BIAS_7_REG_ID} := FF_GLOBAL_BL_BIAS_7_REG_WIDTH   ; \
p_data_width{HW_ASSR_CLEAR_REG_ID} := HW_ASSR_CLEAR_REG_WIDTH   ; \
p_data_width{HW_ASSR_MASK_REG_ID} := HW_ASSR_MASK_REG_WIDTH   ; \
p_data_width{HW_ASSR_RAW_STAT_REG_ID} := HW_ASSR_RAW_STAT_REG_WIDTH   ; \
p_data_width{HW_ASSR_STAT_REG_ID} := HW_ASSR_STAT_REG_WIDTH   ; \
p_data_width{PWR_FEATURE_REG_ID} := PWR_FEATURE_REG_WIDTH   ; \
\
FEATURE c_reg_rst_val                             : D1<BITVECTOR>; \
c_reg_rst_val{DFD_DATA_READ_CMD_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(DFD_DATA_READ_CMD_REG_RSTVAL), p_data_width{DFD_DATA_READ_CMD_REG_ID})); \
c_reg_rst_val{DFD_DATA_READ_COMPLETION_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(DFD_DATA_READ_COMPLETION_REG_RSTVAL), p_data_width{DFD_DATA_READ_COMPLETION_REG_ID})); \
c_reg_rst_val{DFD_EN_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(DFD_EN_REG_RSTVAL), p_data_width{DFD_EN_REG_ID})); \
c_reg_rst_val{DFD_SINGLE_STEP_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(DFD_SINGLE_STEP_REG_RSTVAL), p_data_width{DFD_SINGLE_STEP_REG_ID})); \
c_reg_rst_val{DFD_TRACED_DATA_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(DFD_TRACED_DATA_REG_RSTVAL), p_data_width{DFD_TRACED_DATA_REG_ID})); \
c_reg_rst_val{DFD_TRACED_DATA_VALID_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(DFD_TRACED_DATA_VALID_REG_RSTVAL), p_data_width{DFD_TRACED_DATA_VALID_REG_ID})); \
c_reg_rst_val{FF_GBL_GRD_CFG0_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(FF_GBL_GRD_CFG0_REG_RSTVAL), p_data_width{FF_GBL_GRD_CFG0_REG_ID})); \
c_reg_rst_val{FF_GBL_GRD_CFG1_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(FF_GBL_GRD_CFG1_REG_RSTVAL), p_data_width{FF_GBL_GRD_CFG1_REG_ID})); \
c_reg_rst_val{FF_GBL_GRD_CFG2_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(FF_GBL_GRD_CFG2_REG_RSTVAL), p_data_width{FF_GBL_GRD_CFG2_REG_ID})); \
c_reg_rst_val{FF_GLOBAL_BL_BIAS_0_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(FF_GLOBAL_BL_BIAS_0_REG_RSTVAL), p_data_width{FF_GLOBAL_BL_BIAS_0_REG_ID})); \
c_reg_rst_val{FF_GLOBAL_BL_BIAS_1_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(FF_GLOBAL_BL_BIAS_1_REG_RSTVAL), p_data_width{FF_GLOBAL_BL_BIAS_1_REG_ID})); \
c_reg_rst_val{FF_GLOBAL_BL_BIAS_2_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(FF_GLOBAL_BL_BIAS_2_REG_RSTVAL), p_data_width{FF_GLOBAL_BL_BIAS_2_REG_ID})); \
c_reg_rst_val{FF_GLOBAL_BL_BIAS_3_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(FF_GLOBAL_BL_BIAS_3_REG_RSTVAL), p_data_width{FF_GLOBAL_BL_BIAS_3_REG_ID})); \
c_reg_rst_val{FF_GLOBAL_BL_BIAS_4_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(FF_GLOBAL_BL_BIAS_4_REG_RSTVAL), p_data_width{FF_GLOBAL_BL_BIAS_4_REG_ID})); \
c_reg_rst_val{FF_GLOBAL_BL_BIAS_5_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(FF_GLOBAL_BL_BIAS_5_REG_RSTVAL), p_data_width{FF_GLOBAL_BL_BIAS_5_REG_ID})); \
c_reg_rst_val{FF_GLOBAL_BL_BIAS_6_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(FF_GLOBAL_BL_BIAS_6_REG_RSTVAL), p_data_width{FF_GLOBAL_BL_BIAS_6_REG_ID})); \
c_reg_rst_val{FF_GLOBAL_BL_BIAS_7_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(FF_GLOBAL_BL_BIAS_7_REG_RSTVAL), p_data_width{FF_GLOBAL_BL_BIAS_7_REG_ID})); \
c_reg_rst_val{HW_ASSR_CLEAR_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(HW_ASSR_CLEAR_REG_RSTVAL), p_data_width{HW_ASSR_CLEAR_REG_ID})); \
c_reg_rst_val{HW_ASSR_MASK_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(HW_ASSR_MASK_REG_RSTVAL), p_data_width{HW_ASSR_MASK_REG_ID})); \
c_reg_rst_val{HW_ASSR_RAW_STAT_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(HW_ASSR_RAW_STAT_REG_RSTVAL), p_data_width{HW_ASSR_RAW_STAT_REG_ID})); \
c_reg_rst_val{HW_ASSR_STAT_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(HW_ASSR_STAT_REG_RSTVAL), p_data_width{HW_ASSR_STAT_REG_ID})); \
c_reg_rst_val{PWR_FEATURE_REG_ID} := BITVECTOR(TO_UNSIGNED(NATURAL(PWR_FEATURE_REG_RSTVAL), p_data_width{PWR_FEATURE_REG_ID})); \
\
FEATURE p_reg_wmask                             : D1<BITVECTOR>;  \
 p_reg_wmask{DFD_DATA_READ_CMD_REG_ID}  := X"00000001";\
 p_reg_wmask{DFD_DATA_READ_COMPLETION_REG_ID}  := X"00000000";\
 p_reg_wmask{DFD_EN_REG_ID}  := X"00000111";\
 p_reg_wmask{DFD_SINGLE_STEP_REG_ID}  := X"00000001";\
 p_reg_wmask{DFD_TRACED_DATA_REG_ID}  := X"00000000";\
 p_reg_wmask{DFD_TRACED_DATA_VALID_REG_ID}  := X"00000000";\
 p_reg_wmask{FF_GBL_GRD_CFG0_REG_ID}  := X"FFFFFFFF";\
 p_reg_wmask{FF_GBL_GRD_CFG1_REG_ID}  := X"7FFF7FFF";\
 p_reg_wmask{FF_GBL_GRD_CFG2_REG_ID}  := X"000307FF";\
 p_reg_wmask{FF_GLOBAL_BL_BIAS_0_REG_ID}  := X"FFFFFFFF";\
 p_reg_wmask{FF_GLOBAL_BL_BIAS_1_REG_ID}  := X"FFFFFFFF";\
 p_reg_wmask{FF_GLOBAL_BL_BIAS_2_REG_ID}  := X"FFFFFFFF";\
 p_reg_wmask{FF_GLOBAL_BL_BIAS_3_REG_ID}  := X"FFFFFFFF";\
 p_reg_wmask{FF_GLOBAL_BL_BIAS_4_REG_ID}  := X"FFFFFFFF";\
 p_reg_wmask{FF_GLOBAL_BL_BIAS_5_REG_ID}  := X"FFFFFFFF";\
 p_reg_wmask{FF_GLOBAL_BL_BIAS_6_REG_ID}  := X"FFFFFFFF";\
 p_reg_wmask{FF_GLOBAL_BL_BIAS_7_REG_ID}  := X"FFFFFFFF";\
 p_reg_wmask{HW_ASSR_CLEAR_REG_ID}  := X"0000000F";\
 p_reg_wmask{HW_ASSR_MASK_REG_ID}  := X"0000000F";\
 p_reg_wmask{HW_ASSR_RAW_STAT_REG_ID}  := X"00000000";\
 p_reg_wmask{HW_ASSR_STAT_REG_ID}  := X"00000000";\
 p_reg_wmask{PWR_FEATURE_REG_ID}  := X"00000003";\
\
FEATURE p_reg_rmask                             : D1<BITVECTOR>;  \
 p_reg_rmask{DFD_DATA_READ_CMD_REG_ID}  := X"00000001";\
 p_reg_rmask{DFD_DATA_READ_COMPLETION_REG_ID}  := X"00000001";\
 p_reg_rmask{DFD_EN_REG_ID}  := X"00000111";\
 p_reg_rmask{DFD_SINGLE_STEP_REG_ID}  := X"00000001";\
 p_reg_rmask{DFD_TRACED_DATA_REG_ID}  := X"FFFFFFFF";\
 p_reg_rmask{DFD_TRACED_DATA_VALID_REG_ID}  := X"00000001";\
 p_reg_rmask{FF_GBL_GRD_CFG0_REG_ID}  := X"FFFFFFFF";\
 p_reg_rmask{FF_GBL_GRD_CFG1_REG_ID}  := X"7FFF7FFF";\
 p_reg_rmask{FF_GBL_GRD_CFG2_REG_ID}  := X"000307FF";\
 p_reg_rmask{FF_GLOBAL_BL_BIAS_0_REG_ID}  := X"FFFFFFFF";\
 p_reg_rmask{FF_GLOBAL_BL_BIAS_1_REG_ID}  := X"FFFFFFFF";\
 p_reg_rmask{FF_GLOBAL_BL_BIAS_2_REG_ID}  := X"FFFFFFFF";\
 p_reg_rmask{FF_GLOBAL_BL_BIAS_3_REG_ID}  := X"FFFFFFFF";\
 p_reg_rmask{FF_GLOBAL_BL_BIAS_4_REG_ID}  := X"FFFFFFFF";\
 p_reg_rmask{FF_GLOBAL_BL_BIAS_5_REG_ID}  := X"FFFFFFFF";\
 p_reg_rmask{FF_GLOBAL_BL_BIAS_6_REG_ID}  := X"FFFFFFFF";\
 p_reg_rmask{FF_GLOBAL_BL_BIAS_7_REG_ID}  := X"FFFFFFFF";\
 p_reg_rmask{HW_ASSR_CLEAR_REG_ID}  := X"0000000F";\
 p_reg_rmask{HW_ASSR_MASK_REG_ID}  := X"0000000F";\
 p_reg_rmask{HW_ASSR_RAW_STAT_REG_ID}  := X"0000000F";\
 p_reg_rmask{HW_ASSR_STAT_REG_ID}  := X"0000000F";\
 p_reg_rmask{PWR_FEATURE_REG_ID}  := X"00000003";\
\
FEATURE p_reg_womask                             : D1<BITVECTOR>;  \
 p_reg_womask{DFD_DATA_READ_CMD_REG_ID}  := X"00000000";\
 p_reg_womask{DFD_DATA_READ_COMPLETION_REG_ID}  := X"00000000";\
 p_reg_womask{DFD_EN_REG_ID}  := X"00000000";\
 p_reg_womask{DFD_SINGLE_STEP_REG_ID}  := X"00000000";\
 p_reg_womask{DFD_TRACED_DATA_REG_ID}  := X"00000000";\
 p_reg_womask{DFD_TRACED_DATA_VALID_REG_ID}  := X"00000000";\
 p_reg_womask{FF_GBL_GRD_CFG0_REG_ID}  := X"00000000";\
 p_reg_womask{FF_GBL_GRD_CFG1_REG_ID}  := X"00000000";\
 p_reg_womask{FF_GBL_GRD_CFG2_REG_ID}  := X"00000000";\
 p_reg_womask{FF_GLOBAL_BL_BIAS_0_REG_ID}  := X"00000000";\
 p_reg_womask{FF_GLOBAL_BL_BIAS_1_REG_ID}  := X"00000000";\
 p_reg_womask{FF_GLOBAL_BL_BIAS_2_REG_ID}  := X"00000000";\
 p_reg_womask{FF_GLOBAL_BL_BIAS_3_REG_ID}  := X"00000000";\
 p_reg_womask{FF_GLOBAL_BL_BIAS_4_REG_ID}  := X"00000000";\
 p_reg_womask{FF_GLOBAL_BL_BIAS_5_REG_ID}  := X"00000000";\
 p_reg_womask{FF_GLOBAL_BL_BIAS_6_REG_ID}  := X"00000000";\
 p_reg_womask{FF_GLOBAL_BL_BIAS_7_REG_ID}  := X"00000000";\
 p_reg_womask{HW_ASSR_CLEAR_REG_ID}  := X"00000000";\
 p_reg_womask{HW_ASSR_MASK_REG_ID}  := X"00000000";\
 p_reg_womask{HW_ASSR_RAW_STAT_REG_ID}  := X"00000000";\
 p_reg_womask{HW_ASSR_STAT_REG_ID}  := X"00000000";\
 p_reg_womask{PWR_FEATURE_REG_ID}  := X"00000000";\
\
FEATURE p_reg_romask                             : D1<BITVECTOR>;  \
 p_reg_romask{DFD_DATA_READ_CMD_REG_ID}  := X"00000000";\
 p_reg_romask{DFD_DATA_READ_COMPLETION_REG_ID}  := X"00000001";\
 p_reg_romask{DFD_EN_REG_ID}  := X"00000000";\
 p_reg_romask{DFD_SINGLE_STEP_REG_ID}  := X"00000000";\
 p_reg_romask{DFD_TRACED_DATA_REG_ID}  := X"FFFFFFFF";\
 p_reg_romask{DFD_TRACED_DATA_VALID_REG_ID}  := X"00000001";\
 p_reg_romask{FF_GBL_GRD_CFG0_REG_ID}  := X"00000000";\
 p_reg_romask{FF_GBL_GRD_CFG1_REG_ID}  := X"00000000";\
 p_reg_romask{FF_GBL_GRD_CFG2_REG_ID}  := X"00000000";\
 p_reg_romask{FF_GLOBAL_BL_BIAS_0_REG_ID}  := X"00000000";\
 p_reg_romask{FF_GLOBAL_BL_BIAS_1_REG_ID}  := X"00000000";\
 p_reg_romask{FF_GLOBAL_BL_BIAS_2_REG_ID}  := X"00000000";\
 p_reg_romask{FF_GLOBAL_BL_BIAS_3_REG_ID}  := X"00000000";\
 p_reg_romask{FF_GLOBAL_BL_BIAS_4_REG_ID}  := X"00000000";\
 p_reg_romask{FF_GLOBAL_BL_BIAS_5_REG_ID}  := X"00000000";\
 p_reg_romask{FF_GLOBAL_BL_BIAS_6_REG_ID}  := X"00000000";\
 p_reg_romask{FF_GLOBAL_BL_BIAS_7_REG_ID}  := X"00000000";\
 p_reg_romask{HW_ASSR_CLEAR_REG_ID}  := X"00000000";\
 p_reg_romask{HW_ASSR_MASK_REG_ID}  := X"00000000";\
 p_reg_romask{HW_ASSR_RAW_STAT_REG_ID}  := X"0000000F";\
 p_reg_romask{HW_ASSR_STAT_REG_ID}  := X"0000000F";\
 p_reg_romask{PWR_FEATURE_REG_ID}  := X"00000000";\
\
FEATURE p_func_en                             : D1<BOOLEAN>;  \
 p_func_en{DFD_DATA_READ_CMD_REG_ID}  := FALSE; \
 p_func_en{DFD_DATA_READ_COMPLETION_REG_ID}  := TRUE; \
 p_func_en{DFD_EN_REG_ID}  := FALSE; \
 p_func_en{DFD_SINGLE_STEP_REG_ID}  := FALSE; \
 p_func_en{DFD_TRACED_DATA_REG_ID}  := TRUE; \
 p_func_en{DFD_TRACED_DATA_VALID_REG_ID}  := TRUE; \
 p_func_en{FF_GBL_GRD_CFG0_REG_ID}  := FALSE; \
 p_func_en{FF_GBL_GRD_CFG1_REG_ID}  := FALSE; \
 p_func_en{FF_GBL_GRD_CFG2_REG_ID}  := FALSE; \
 p_func_en{FF_GLOBAL_BL_BIAS_0_REG_ID}  := FALSE; \
 p_func_en{FF_GLOBAL_BL_BIAS_1_REG_ID}  := FALSE; \
 p_func_en{FF_GLOBAL_BL_BIAS_2_REG_ID}  := FALSE; \
 p_func_en{FF_GLOBAL_BL_BIAS_3_REG_ID}  := FALSE; \
 p_func_en{FF_GLOBAL_BL_BIAS_4_REG_ID}  := FALSE; \
 p_func_en{FF_GLOBAL_BL_BIAS_5_REG_ID}  := FALSE; \
 p_func_en{FF_GLOBAL_BL_BIAS_6_REG_ID}  := FALSE; \
 p_func_en{FF_GLOBAL_BL_BIAS_7_REG_ID}  := FALSE; \
 p_func_en{HW_ASSR_CLEAR_REG_ID}  := FALSE; \
 p_func_en{HW_ASSR_MASK_REG_ID}  := FALSE; \
 p_func_en{HW_ASSR_RAW_STAT_REG_ID}  := TRUE; \
 p_func_en{HW_ASSR_STAT_REG_ID}  := TRUE; \
 p_func_en{PWR_FEATURE_REG_ID}  := FALSE; \


#define FF_GBL_CCBCR_SIGNALS \
SIGNAL func_en                                : D1<BIT>(FF_GBL_NOF_REGS_BANK); \
SIGNAL wire_reg_we                            : D1<BIT>(FF_GBL_NOF_REGS_BANK); \
SIGNAL wire_reg_outputs                       : D1<BITVECTOR>(p_data_width); \
SIGNAL func_data                              : D1<BITVECTOR>(p_data_width);

#define DFD_DATA_READ_CMD_FETCH_RANGE   0 
#define DFD_DATA_READ_COMPLETION_RD_COMP_RANGE   0 
#define DFD_EN_DFD_EN_RANGE   0 
#define DFD_EN_USE_PREV_TRACE_CHAIN_RANGE   8 
#define DFD_EN_USE_PREV_TRIG_CHAIN_RANGE   4 
#define DFD_SINGLE_STEP_SINGLE_STEP_RANGE   0 
#define DFD_TRACED_DATA_DFD_TRACED_DATA_RANGE   31 DOWNTO 0 
#define DFD_TRACED_DATA_VALID_DATA_VALID_RANGE   0 
#define FF_GBL_GRD_CFG0_BLOCK_HEIGHT_RANGE   23 DOWNTO 20 
#define FF_GBL_GRD_CFG0_BLOCK_WIDTH_RANGE   19 DOWNTO 16 
#define FF_GBL_GRD_CFG0_GRID_HEIGHT_RANGE   15 DOWNTO 8 
#define FF_GBL_GRD_CFG0_GRID_HEIGHT_PER_SLICE_RANGE   31 DOWNTO 24 
#define FF_GBL_GRD_CFG0_GRID_WIDTH_RANGE   7 DOWNTO 0 
#define FF_GBL_GRD_CFG1_X_START_RANGE   14 DOWNTO 0 
#define FF_GBL_GRD_CFG1_Y_START_RANGE   30 DOWNTO 16 
#define FF_GBL_GRD_CFG2_FF_EN_RANGE   10 
#define FF_GBL_GRD_CFG2_GLOBAL_BL_EN_RANGE   9 
#define FF_GBL_GRD_CFG2_GRID_BL_EN_RANGE   8 
#define FF_GBL_GRD_CFG2_SENSOR_MODE_RANGE   17 DOWNTO 16 
#define FF_GBL_GRD_CFG2_INIT_SET_VRT_OFFST_UL_RANGE   7 DOWNTO 0 
#define FF_GLOBAL_BL_BIAS_0_FIXOBC00_RANGE   15 DOWNTO 0 
#define FF_GLOBAL_BL_BIAS_0_FIXOBC01_RANGE   31 DOWNTO 16 
#define FF_GLOBAL_BL_BIAS_1_FIXOBC02_RANGE   15 DOWNTO 0 
#define FF_GLOBAL_BL_BIAS_1_FIXOBC03_RANGE   31 DOWNTO 16 
#define FF_GLOBAL_BL_BIAS_2_FIXOBC10_RANGE   15 DOWNTO 0 
#define FF_GLOBAL_BL_BIAS_2_FIXOBC11_RANGE   31 DOWNTO 16 
#define FF_GLOBAL_BL_BIAS_3_FIXOBC12_RANGE   15 DOWNTO 0 
#define FF_GLOBAL_BL_BIAS_3_FIXOBC13_RANGE   31 DOWNTO 16 
#define FF_GLOBAL_BL_BIAS_4_FIXOBC20_RANGE   15 DOWNTO 0 
#define FF_GLOBAL_BL_BIAS_4_FIXOBC21_RANGE   31 DOWNTO 16 
#define FF_GLOBAL_BL_BIAS_5_FIXOBC22_RANGE   15 DOWNTO 0 
#define FF_GLOBAL_BL_BIAS_5_FIXOBC23_RANGE   31 DOWNTO 16 
#define FF_GLOBAL_BL_BIAS_6_FIXOBC30_RANGE   15 DOWNTO 0 
#define FF_GLOBAL_BL_BIAS_6_FIXOBC31_RANGE   31 DOWNTO 16 
#define FF_GLOBAL_BL_BIAS_7_FIXOBC32_RANGE   15 DOWNTO 0 
#define FF_GLOBAL_BL_BIAS_7_FIXOBC33_RANGE   31 DOWNTO 16 
#define HW_ASSR_CLEAR_CLEAR_RANGE   3 DOWNTO 0 
#define HW_ASSR_MASK_MASK_RANGE   3 DOWNTO 0 
#define HW_ASSR_RAW_STAT_STAT_RANGE   3 DOWNTO 0 
#define HW_ASSR_STAT_STAT_RANGE   3 DOWNTO 0 
#define PWR_FEATURE_EMPTY_EN_RANGE   0 
#define PWR_FEATURE_MOL_EN_RANGE   1 

#define DFD_DATA_READ_CMD_FETCH_WIDTH  1
#define DFD_DATA_READ_COMPLETION_RD_COMP_WIDTH  1
#define DFD_EN_DFD_EN_WIDTH  1
#define DFD_EN_USE_PREV_TRACE_CHAIN_WIDTH  1
#define DFD_EN_USE_PREV_TRIG_CHAIN_WIDTH  1
#define DFD_SINGLE_STEP_SINGLE_STEP_WIDTH  1
#define DFD_TRACED_DATA_DFD_TRACED_DATA_WIDTH  32
#define DFD_TRACED_DATA_VALID_DATA_VALID_WIDTH  1
#define FF_GBL_GRD_CFG0_BLOCK_HEIGHT_WIDTH  4
#define FF_GBL_GRD_CFG0_BLOCK_WIDTH_WIDTH  4
#define FF_GBL_GRD_CFG0_GRID_HEIGHT_PER_SLICE_WIDTH  8
#define FF_GBL_GRD_CFG0_GRID_HEIGHT_WIDTH  8
#define FF_GBL_GRD_CFG0_GRID_WIDTH_WIDTH  8
#define FF_GBL_GRD_CFG1_X_START_WIDTH  15
#define FF_GBL_GRD_CFG1_Y_START_WIDTH  15
#define FF_GBL_GRD_CFG2_FF_EN_WIDTH  1
#define FF_GBL_GRD_CFG2_GLOBAL_BL_EN_WIDTH  1
#define FF_GBL_GRD_CFG2_GRID_BL_EN_WIDTH  1
#define FF_GBL_GRD_CFG2_INIT_SET_VRT_OFFST_UL_WIDTH  8
#define FF_GBL_GRD_CFG2_SENSOR_MODE_WIDTH  2
#define FF_GLOBAL_BL_BIAS_0_FIXOBC00_WIDTH  16
#define FF_GLOBAL_BL_BIAS_0_FIXOBC01_WIDTH  16
#define FF_GLOBAL_BL_BIAS_1_FIXOBC02_WIDTH  16
#define FF_GLOBAL_BL_BIAS_1_FIXOBC03_WIDTH  16
#define FF_GLOBAL_BL_BIAS_2_FIXOBC10_WIDTH  16
#define FF_GLOBAL_BL_BIAS_2_FIXOBC11_WIDTH  16
#define FF_GLOBAL_BL_BIAS_3_FIXOBC12_WIDTH  16
#define FF_GLOBAL_BL_BIAS_3_FIXOBC13_WIDTH  16
#define FF_GLOBAL_BL_BIAS_4_FIXOBC20_WIDTH  16
#define FF_GLOBAL_BL_BIAS_4_FIXOBC21_WIDTH  16
#define FF_GLOBAL_BL_BIAS_5_FIXOBC22_WIDTH  16
#define FF_GLOBAL_BL_BIAS_5_FIXOBC23_WIDTH  16
#define FF_GLOBAL_BL_BIAS_6_FIXOBC30_WIDTH  16
#define FF_GLOBAL_BL_BIAS_6_FIXOBC31_WIDTH  16
#define FF_GLOBAL_BL_BIAS_7_FIXOBC32_WIDTH  16
#define FF_GLOBAL_BL_BIAS_7_FIXOBC33_WIDTH  16
#define HW_ASSR_CLEAR_CLEAR_WIDTH  4
#define HW_ASSR_MASK_MASK_WIDTH  4
#define HW_ASSR_RAW_STAT_STAT_WIDTH  4
#define HW_ASSR_STAT_STAT_WIDTH  4
#define PWR_FEATURE_EMPTY_EN_WIDTH  1
#define PWR_FEATURE_MOL_EN_WIDTH  1


#endif
