/*  sdw_registers.h - SoundWire MIPI spec 1.0 defined SoundWire slave
 *			register definition file. This defines the register
 *			offsets, bit masks and shifts in accordance with
 *			mipi spec 1.0
 *  Copyright (C) 2015-2016 Intel Corp
 *  Author:  Hardik T Shah <hardik.t.shah@intel.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#ifndef _LINUX_SDW_REG_H
#define _LINUX_SDW_REG_H

#define SDW_NUM_DATA_PORT_REGISTERS			0x100
#define SDW_BANK1_REGISTER_OFFSET			0x10

#define SDW_DP0_INTSTAT					0x0
#define SDW_DP0_INTSTAT_TEST_FAIL_MASK			0x1
#define SDW_DP0_INTSTAT_TEST_FAIL_SHIFT			0x2
#define SDW_DP0_INTSTAT_PORT_READY_MASK			0x4
#define SDW_DP0_INTSTAT_PORT_READY_SHIFT		0x20
#define SDW_DP0_INTSTAT_BRA_FAILURE_MASK		0x40
#define SDW_DP0_INTSTAT_BRA_FAILURE_SHIFT		0x80

#define SDW_DP0_INTCLEAR				0x0
#define SDW_DP0_INTCLEAR_TEST_FAIL_MASK			0x1
#define SDW_DP0_INTCLEAR_PORT_READY_MASK		0x2
#define SDW_DP0_INTCLEAR_BRA_FAILURE_MASK		0x4
#define SDW_DP0_INTSTAT_IMPDEF1_MASK			0x20
#define SDW_DP0_INTSTAT_IMPDEF2_MASK			0x40
#define SDW_DP0_INTSTAT_IMPDEF3_MASK			0x80

#define SDW_DP0_INTMASK					0x1
#define SDW_DP0_INTMASK_TEST_FAIL_MASK			0x1
#define SDW_DP0_INTMASK_PORT_READY_MASK			0x2
#define SDW_DP0_INTMASK_BRA_FAILURE_MASK		0x4
#define SDW_DP0_INTMASK_IMPDEF1_MASK			0x20
#define SDW_DP0_INTMASK_IMPDEF2_MASK			0x40
#define SDW_DP0_INTMASK_IMPDEF3_MASK			0x80

#define SDW_DP0_PORTCTRL				0x2
#define SDW_DP0_PORTCTRL_PORTDATAMODE_MASK		0x3
#define SDW_DP0_PORTCTRL_PORTDATAMODE_SHIFT		2
#define SDW_DP0_PORTCTRL_NEXTINVERTBANK_MASK		0x1
#define SDW_DP0_PORTCTRL_NEXTINVERTBANK_SHIFT		4

#define SDW_DP0_BLOCKCTRL1				0x3

#define SDW_DP0_PREPARESTATUS				0x4

#define SDW_DP0_PREPARECTRL				0x5

#define SDW_DP0_CHANNELEN				0x20
#define SDW_DP0_SAMPLECTRL1				0x22
#define SDW_DP0_SAMPLECTRL2				0x23
#define SDW_DP0_OFFSETCTRL1				0x24
#define SDW_DP0_OFFSETCTRL2				0x25
#define SDW_DP0_HCTRL					0x26
#define SDW_DP0_LANECTRL				0x28

#define SDW_SCP_INTSTAT_1				0x40
#define SDW_SCP_INTSTAT1_PARITY_MASK			0x1
#define SDW_SCP_INTSTAT1_BUS_CLASH_MASK			0x2
#define SDW_SCP_INTSTAT1_IMPL_DEF_MASK			0x4
#define SDW_SCP_INTSTAT1_SCP2_CASCADE_MASK		0x80

#define SDW_SCP_INTCLEAR1				0x40
#define SDW_SCP_INTCLEAR1_PARITY_MASK			0x1
#define SDW_SCP_INTCLEAR1_BUS_CLASH_MASK		0x2
#define SDW_SCP_INTCLEAR1_IMPL_DEF_MASK			0x4
#define SDW_SCP_INTCLEAR1_SCP2_CASCADE_MASK		0x80
#define SDW_SCP_INTMASK1                                0x41
#define SDW_SCP_INTMASK1_PARITY_MASK                    0x1
#define SDW_SCP_INTMASK1_BUS_CLASH_MASK			0x2
#define SDW_SCP_INTSTAT2				0x42
#define SDW_SCP_INTSTAT2_SCP3_CASCADE_MASK		0x80
#define SDW_SCP_INTSTAT3				0x43
#define SDW_SCP_CTRL					0x44
#define SDW_SCP_CTRL_CLK_STP_NOW_MASK			0x1
#define SDW_SCP_CTRL_CLK_STP_NOW_SHIFT			0x1
#define SDW_SCP_STAT					0x44
#define SDW_SCP_STAT_CLK_STP_NF_MASK			0x1
#define SDW_SCP_SYSTEMCTRL				0x45
#define SDW_SCP_SYSTEMCTRL_CLK_STP_PREP_MASK		0x1
#define SDW_SCP_SYSTEMCTRL_CLK_STP_PREP_SHIFT		0x0
#define SDW_SCP_SYSTEMCTRL_CLK_STP_MODE_SHIFT		0x1
#define SDW_SCP_SYSTEMCTRL_WAKE_UP_EN_SHIFT		0x2
#define SDW_SCP_SYSTEMCTRL_HIGH_PHY_SHIFT		0x3

#define SDW_SCP_DEVNUMBER				0x46
#define SDW_SCP_HIGH_PHY_CHECK				0x47
#define SDW_SCP_ADDRPAGE1				0x48
#define SDW_SCP_ADDRPAGE2				0x49
#define SDW_SCP_KEEPEREN				0x4A
#define SDW_SCP_BANKDELAY				0x4B
#define SDW_SCP_TESTMODE				0x4F
#define SDW_SCP_DEVID_0					0x50
#define SDW_SCP_DEVID_1					0x51
#define SDW_SCP_DEVID_2					0x52
#define SDW_SCP_DEVID_3					0x53
#define SDW_SCP_DEVID_4					0x54
#define SDW_SCP_DEVID_5					0x55

/* Banked Registers */
#define SDW_SCP_FRAMECTRL				0x60
#define SDW_SCP_NEXTFRAME				0x61

#define SDW_DPN_INTSTAT					0x0
#define SDW_DPN_INTSTAT_TEST_FAIL_MASK			0x1
#define SDW_DPN_INTSTAT_PORT_READY_MASK			0x2
#define SDW_DPN_INTSTAT_IMPDEF1_MASK			0x20
#define SDW_DPN_INTSTAT_IMPDEF2_MASK			0x40
#define SDW_DPN_INTSTAT_IMPDEF3_MASK			0x80

#define SDW_DPN_INTCLEAR				0x0
#define SDW_DPN_INTCLEAR_TEST_FAIL_MASK			0x1
#define SDW_DPN_INTCLEAR_PORT_READY_MASK		0x2
#define SDW_DPN_INTCLEAR_IMPDEF1_MASK			0x20
#define SDW_DPN_INTCLEAR_IMPDEF2_MASK			0x40
#define SDW_DPN_INTCLEAR_IMPDEF3_MASK			0x80

#define SDW_DPN_INTMASK					0x1
#define SDW_DPN_PORTCTRL				0x2
#define SDW_DPN_PORTCTRL_PORTFLOWMODE_MASK		0x3
#define SDW_DPN_PORTCTRL_PORTFLOWMODE_SHIFT		0
#define SDW_DPN_PORTCTRL_PORTDATAMODE_MASK		0x3
#define SDW_DPN_PORTCTRL_PORTDATAMODE_SHIFT		2
#define SDW_DPN_PORTCTRL_NEXTINVERTBANK_MASK		0x1
#define SDW_DPN_PORTCTRL_NEXTINVERTBANK_SHIFT		4

#define SDW_DPN_BLOCKCTRL1				0x3
#define SDW_DPN_BLOCKCTRL1_WORDLENGTH_MASK		0x3F
#define SDW_DPN_BLOCKCTRL1_WORDLENGTH_SHIFT		0

#define SDW_DPN_PREPARESTATUS				0x4
#define SDW_DPN_PREPARECTRL				0x5
#define SDW_DPN_PREPARECTRL_CH_PREPARE_MASK		0xFF

#define SDW_DPN_CHANNELEN				0x20
#define SDW_DPN_BLOCKCTRL2				0x21
#define SDW_DPN_SAMPLECTRL1				0x22
#define SDW_DPN_SAMPLECTRL1_LOW_MASK			0xFF
#define SDW_DPN_SAMPLECTRL2				0x23
#define SDW_DPN_SAMPLECTRL2_LOW_MASK			0xFF00
#define SDW_DPN_OFFSETCTRL1				0x24
#define SDW_DPN_OFFSETCTRL2				0x25
#define SDW_DPN_HCTRL					0x26
#define SDW_DPN_HCTRL_HSTART_MASK			0xF
#define SDW_DPN_HCTRL_HSTOP_MASK			0xF
#define SDW_DPN_HCTRL_HSTART_SHIFT			4
#define SDW_DPN_HCTRL_HSTOP_SHIFT			0
#define SDW_DPN_BLOCKCTRL3				0x27
#define SDW_DPN_LANECTRL				0x28

#endif
