nvhost-t20-objs  = \
	t20.o \
	syncpt_t20.o \
	cpuaccess_t20.o \
	channel_t20.o \
	intr_t20.o \
	cdma_t20.o \
	3dctx_t20.o \
	debug_t20.o

obj-$(CONFIG_TEGRA_GRHOST) += nvhost-t20.o

include $(srctree)/compat26/Makefile.inc
