subdir-ccflags-y += -Werror
obj-$(CONFIG_ARCH_TEGRA_21x_SOC)	+= bpmp_t210.o
obj-$(CONFIG_ARCH_TEGRA_21x_SOC)	+= mail_t210.o
obj-$(CONFIG_DEBUG_FS)			+= fwdebug.o
obj-y					+= bpmp.o
obj-y					+= mail.o
obj-y					+= mailman.o
