# SPDX-License-Identifier: GPL-2.0+
# Raven Ridge platform Support
snd-pci-acp3x-objs	:= pci-acp3x.o
snd-acp3x-pcm-dma-objs	:= acp3x-pcm-dma.o
snd-soc-dummy-w5102-objs := dummy-w5102.o
snd-soc-acp3x-mach-objs := acp3x-dummy5102.o
obj-$(CONFIG_SND_SOC_AMD_ACP3x)	 += snd-pci-acp3x.o
obj-$(CONFIG_SND_SOC_AMD_ACP3x)	 += snd-acp3x-pcm-dma.o
obj-$(CONFIG_SND_SOC_AMD_ACP3x)	+= snd-soc-dummy-w5102.o
obj-$(CONFIG_SND_SOC_AMD_ACP3x)	+= snd-soc-acp3x-mach.o
