#
# Makefile for IIO proximity sensors
#

# When adding new entries keep the list in alphabetical order
obj-$(CONFIG_AS3935)		+= as3935.o
GCOV_PROFILE := y

ccflags-y += -Werror
obj-$(CONFIG_NVS_IQS2X3)	+= nvs_iqs2x3.o

