obj-y += fuse/

obj-y += common.o
obj-y += pmc.o

obj-$(CONFIG_TEGRA_LEGACY_FUSE) += legacy-fuse/
obj-$(CONFIG_TEGRA_LEGACY_PROC) += legacy-proc.o
obj-$(CONFIG_TEGRA_LOADER_TIMES) += loader-times.o
obj-$(CONFIG_ARCH_TEGRA_3x_SOC) += tesla-boardrev.o

