dtb-$(CONFIG_ARCH_TRAV) += \
    turbo-trav-board-rev0.dtb \
    turbo-trav-board-rev-b0.dtb \
    turbo-trav-cts-board-rev0.dtb \
    turbo-trav-slt-board-rev0.dtb \
    turbo-trav-eval-ml2-dev05.dtb \
    turbo-trav-eval-ml3-dev03-hotfix01.dtb \
    turbo-trav-board-hw31.dtb \
    turbo-trav-board-hw31-revb.dtb \
    turbo-trav-eval-ml4-dev07.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
